### ISSUE TITLE
All permalinks are '?AAAAAA' with v0.9.3

### ISSUE THREAD

**Issue by kriom** [shaarli/Shaarli#1060]
Hi!

Last month I upgraded to `0.9.3`.
Now all `href` attributes of the permalinks of the links list are: `"?AAAAAA"`
I don't use any theme.
You can see it here: https://links.kriom.net/ .

As for issue  #710, permalinks in the rss feed  are valids: https://links.kriom.net/?do=rss

Regards.

**Comment by ArthurHoaro** [comment]
Hi, 

  * From which version did you upgrade? 
  * What's in your `data/updates.txt` file?

**Comment by kriom** [comment]
Hi,
- I upgraded from `0.8.4`
- `cat data/updates.txt`
```
updateMethodMergeDeprecatedConfigFile;updateMethodRenameDashTags;updateMethodConfigToJson;updateMethodEscapeUnescapedConfig;updateMethodDatastoreIds;updateMethodApiSettings;updateMethodDefaultTheme;updateMethodMoveUserCss;updateMethodEscapeMarkdown;updateMethodPiwikUrl;updateMethodAtomDefault;updateMethodCheckUpdateRemoteBranch;updateMethodResetHistoryFile%
```

**Comment by ArthurHoaro** [comment]
That's odd, the ID system change was already done in `v0.8.4`, I don't think there was any major change since then.

  * Can you try to switch to the `default` template to see if the issue is still there (in the configuration page)? Also, while the `vintage` theme is still maintained, it won't receive any new feature, we recommend users to use the `default` theme.
  * You apparently have a fatal error on you `Tag cloud` page (blank page), can you check your web server logs?

**Comment by kriom** [comment]
Hi,

I think you have other fish to fry.
So my solution is: 
- export links
- clean install
- import links
Then, it works perfectly.

You can close this issue.

Thanks you very much !
