### ISSUE TITLE
Recognition of previously shared links & editing

### ISSUE THREAD

**Issue by poVoq** [shaarli/Shaarli#1068]
Hello.

I am using KrISS feed reader a lot to share links into my Shaarli account. One of the issue that cam up is that when linking again to an item already shared previously it directly opens the edit window, see:

https://github.com/tontof/kriss_feed/issues/398#issuecomment-361842553

In general this link recognition is cool, but it only works for logged in users and overall breaks the usability a bit in my case. Would it be possible to link to the permalink instead when the link is recognized, so that non-logged in users can also read the notes when redirected by a share in shaarli link that was previously shared?

Thanks a lot!

**Comment by ArthurHoaro** [comment]
Hi, I'm sorry but I don't understand your use case. Why would non logged in users want to share a link on your Shaarli's instance?

**Comment by poVoq** [comment]
Hmm, I guess this is a rather specific case as Shaarli isn't a multiuser system...

But if you have a 3rd party website that has a "share to shaarli" link that points to a preconfigured Shaarli instance, it would be nice for non-logged in users to see an already shared link when pressing that button, instead of being redirected to the log-in page. Only when the link hasn't be shared yet it should open the editor.

**Comment by ArthurHoaro** [comment]
Oh I see, I didn't understand that your feed reader was public/shared with other users.

Unfortunately, your request goes beyond Shaarli's scope because it wouldn't make sense to redirect someone to a page he didn't ask for. If the request asks to add a new link, Shaarli should serve this page, or failback to the login page.

IMHO, what you ask for should be done by a 3rd party tool matching your link and Shaarli DB, using Shaarli's API.

If others have a different opinion regarding this, please reopen this issue.
