### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by raphaelbastide** [shaarli/Shaarli#1083]
Most of the time I submit a login form, the same login page comes back. When It allows me to actually login, I can’t add new bookmark because the login page comes back on “Save”. I have the same error after a v0.9.0 update.

**Comment by virtualtam** [comment]
Hi @raphaelbastide,

This is most likely related to the HTTP server and/or proxy configuration. Could you provide us with information on how your Shaarli instance is served?

**Comment by raphaelbastide** [comment]
Hello @virtualtam and thank you for your quick answer.  I am not sure what kind of information you are asking but I’ll try: I have PHP 7.0.12 and forced HTTPS. Do you need something else?

**Comment by ArthurHoaro** [comment]
You're issue probably means that the cookies are not set properly. 

  * Can you try with a blank browser profile (without extensions)?
  * Which web server are you using?
  * Can you check that there is no error in your web server log?
  * You can also see using Firefox debugger if the cookie is set to the proper domain/subfolder and that it doesn't change over pages. E.g:

![](http://i.imgur.com/smyH3QN.png)

**Comment by raphaelbastide** [comment]
- I tried with a blank browser, and the issue is the same, it makes me believe it is not a browser related issue.
- I use a server from (Alwaysdata](http://alwaysdata.com/). I have nothing in my server logs.
- The problem doesn’t exist when I bookmark pages that comes from the same address than the one that host my copy of Shaarli
- I noticed in the debugger’s log that I have 2 different address: one begins with a dot `.` the other doesn’t. Is this normal?

![screenshot_2018-02-09_18-25-40](https://user-images.githubusercontent.com/193122/36042067-ec53639a-0dca-11e8-8620-a250dc633d66.png)

**Comment by nodiscc** [comment]
Could something be wrong with your provider's DNS records? It seems that cookies are created from 2 different domains.

Does the same thing happen (cookies from 2 separate domains) in other apps you may be hosting on other subdomains?

If you have setup a server RewriteRule or similar to force HTTPS, could it somehow mangle the URL in an improper way? Does it happen when you disable the rewriterule? Does it happen when you manually input `https://` from the start of the browsing session (without triggering the rewriterule at all)?

**Comment by ArthurHoaro** [comment]
> I noticed in the debugger’s log that I have 2 different address: one begins with a dot . the other doesn’t. Is this normal?

I'm not sure what is causing it, but I have the same thing on the demo/local/personal instances without any issue.

**Comment by CMSplumbear** [comment]
Hi,
Same problem, shaarli instance is also hosted on alwaysdata. Problem seems to be related to IPv6. Alwaysdata has supported IPv6 since long, but it has been enabled globally by default on last thursday (8/2). 
If I force IPv4 on the client (ie, either an entry in /etc/hosts, or disable IPv6 on my box), login works as expected. In the debugger I see two cookies, "shaarli" and "shaarli_StaySignedIn". WIth IPv6 only the first cookie is shown.
In both cases a successful login is reported in data/log.txt

**Comment by ArthurHoaro** [comment]
I ran a few test using their free package. As @CMSplumbear mentionned, the logout comes from the session cookie hijacking protection.

Most of the time, the variable `$_SERVER['REMOTE_ADDR']` is `127.0.0.1`, but sometimes it contains an IPv6 value. So Shaarli see that your IP has changed and logs you out.

Since the issue does not come from Shaarli or IPv6, but rather reverse proxy configuration, I suggest that you disable IP protection and that we close this issue.

**Comment by raphaelbastide** [comment]
I confirm disabling IPv6 on my box solves the issue. Thank you @CMSplumbear @ArthurHoaro
