### ISSUE TITLE
Internal Server Error with Shaarli >v0.8.5

### ISSUE THREAD

**Issue by TalmarGrosskotz** [shaarli/Shaarli#1087]
Hi, i am running Shaarli v0.8.5 successfully on my Cubietruck-Server with Armbian (Apache 2.4.18, php-7, php_intl installed).

When I log in however Shaarli tells me to update to 0.8.5, which is the Version I am actually running. Whenever I try updating (using either Release-File or git) or try running a later version (also both Releasefile or git) I get a `500 Internal Server Error`from my Apache. 

Does anybody have a clue how to fix this?
Thanks.

**Comment by ArthurHoaro** [comment]
Hi, can you check your web server log file to see what the error is?

**Comment by virtualtam** [comment]
Hi @TalmarGrosskotz ,

I confirm this happens on a fresh install of Shaarli `v0.8.5`.

You shouldn't be notified of a new version if:
- your current version is `v0.8.5`
    - this can be verified in `shaarli_version.php`
- Shaarli is configured to check for updates from the `stable` branch
    - this can be verified in `data/config.json.php`

This is due to `shaarli_version.php` not being taken into account and being hardcoded to `0.8.2` in `index.php`: https://github.com/shaarli/Shaarli/blob/v0.8/index.php#L28

I'll release `0.8.6` this week to address this point (and fix related unit tests).

---

Now as 0.8.x is quite old, I would suggest upgrading to a newer version anyway :)

Before upgrading Shaarli, please ensure, that you backup the contents of the `data/` directory (it contains configuration and archived links/bookmarks).

You should be able to find more information about the 500 error by looking at the Apache logs, usually found under `/var/log/apache2/`.

**Comment by TalmarGrosskotz** [comment]
looken into the error log of my apache and found the following:
`[Sun Feb 18 22:16:18.563925 2018] [core:alert] [pid 28084] [client 91.3.32.113:61059] /var/www/html/Shaarli/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a mo
dule not included in the server configuration`

Is this helpful in resolving my problem?

**Comment by TalmarGrosskotz** [comment]
Problem solved!
My Apache installation didn't have rewrite enabled, since I was using redirect for SSL (as suggested by Apache). After enabling rewrite everything worked out fine.

**Comment by virtualtam** [comment]
Good to know you were able to upgrade Shaarli ;-)

I'm keeping this issue open until version checks are fixed for v0.8.x

**Comment by virtualtam** [comment]
[v0.8.6](https://github.com/shaarli/Shaarli/releases/tag/v0.8.6) released!
