### ISSUE TITLE
logged out after a while when using ipv6

### ISSUE THREAD

**Issue by S2-** [shaarli/Shaarli#1106]
I can not understand why this happens, but:
**Steps to reproduce**

- log in to shaarli and make sure that "Disable session cookie hijacking protection" is checked
- log out
- enable ipv6 on client pc and server that hosts shaarli
- log in to shaarli and check "Remember me"
 
**What happens?**

After a while you get logged out of shaarli. I did not understand after how much, but it's less than 24 hours.

**What should happen instead?**

I should not get logged out.

**stuff I tried**

While trying to understand why this happens, I tried the following with ipv6 privacy addresses enabled:

- stopped and restarted apache - still logged in after restart, but not after a while (<24h)
- rebooted my laptop - still logged in after reboot, but not after a while (<24h)
- disabled ipv6 privacy addresses and assigned a static ipv6 address to my client pc - still logged in after address change, but logged out after a while (<24h)
- disbled ipv6 completely and used ipv4 only - still logged in even after a week

```
$ php -v
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by ArthurHoaro** [comment]
Thanks for the detailed report. It's surprising that we never got any issue regarding this, because the *remember me* token is based on the IP address. So if your IP changes, you'll be disconnected after the default session timeout. However, since it's a hash, IPv4 or IPv6 shouldn't change anything.

If I'm not missing anything:
> disabled ipv6 privacy addresses and assigned a static ipv6 address to my client pc - still logged in after address change, but logged out after a while (<24h)

It would have worked if you had logged in after switching to the static IP.

The setting « Disable session cookie hijacking protection » should probably also affect this feature, and ignore the IP address.

**Comment by S2-** [comment]
> The setting « Disable session cookie hijacking protection » should probably also affect this feature, and ignore the IP address.

I thought about that and disabled that feature, but it still logs me out when using ipv6 privacy addresses.

**Comment by ArthurHoaro** [comment]
Yes, what I meant is that we should provide a patch to fix that.
