### ISSUE TITLE
Link Cloudron from install docs

### ISSUE THREAD

**Issue by gramakri** [shaarli/Shaarli#1217]
Hi Shaarli team,
Thanks for Shaarli. We have a Shaarli app on Cloudron (since quite a while now) and we have been maintaining the app package at https://git.cloudron.io/cloudron/shaarli-app (by Felix Bartels). To make sure the automatic updates go smooth, we also have some automated browser tests in the tests/.

You can also try it in our demo at https://my-demo.cloudron.me (username: cloudron password: cloudron).

Would be great if you can add a link to Shaarli's app store page from the install docs to advertise it a bit more.

**Comment by nodiscc** [comment]
Hi @gramakri

Cloudron is already listed here https://github.com/shaarli/Shaarli/blob/master/doc/md/Community-%26-Related-software.md

> Would be great if you can add a link to Shaarli's app store page from the install docs to advertise it a bit more.

Shaarli's technical documentation is not an advertisement for your commercial service. See also https://github.com/Kickball/awesome-selfhosted/issues/1468. Please reopen if you think otherwise.
