### ISSUE TITLE
 Undefined index: sticky

### ISSUE THREAD

**Issue by phil-dyer** [shaarli/Shaarli#1284]
I have just Installed Shaarli v0.10.3 on my home computer a Win10 machine running Apache 2.4.23 and PHP 7.0.9

Everything works well but when not logged in every link I have added shows this error

Notice: Undefined index: sticky in \Shaarli\tmp\linklist.b91ef64efc3688266305ea9b42e5017e.rtpl.php on line 292

**Comment by ArthurHoaro** [comment]
This has been fixed in #1270 however it hasn't been released.

Maybe we should backport this to `0.10` along with #1268? ping @virtualtam

**Comment by virtualtam** [comment]
Yes, we should backport this fix to 0.10. Are there other fixes that should be included? I'll cut a new release next wee(-ish).

**Comment by ArthurHoaro** [comment]
Besides #1268 I don't think there was other bug reported or fixed.

**Comment by anmol26s** [comment]
This issue makes the yunohost fail https://github.com/YunoHost-Apps/shaarli_ynh/tree/testing

**Comment by anmol26s** [comment]
any update on it?

**Comment by virtualtam** [comment]
Hi,

Short answer: it's ready when it's ready.

We planned to backport the corresponding patches a couple weeks back, this has not happened due to lack of time.

> This issue makes the yunohost fail

We did our best in the past to support third-party integrations, including YNH (see #1117, #1118).

If you're that eager to package a given release to provide it through YNH installers, I'd suggest temporarily applying a patch through the corresponding scripts until we publish a new release. This is common practice in the world of software packaging and allows dependees to make software available while upstream sources are updated/fixed.

Anyway, this is just not the best way to get assistance:

> any update on it?

Obviously, no? _(Though ironically, I happen to be cutting v0.10.4 while posting this message... hmm :thinking: )_

This is rude and at best, maintainers will just ignore these posts; at worst, people will get offended (aaaand... ignore or lock these posts).

Maintainers are people too! Think of the maintainers :cat2:

**Comment by nodiscc** [comment]
> I happen to be cutting v0.10.4

I wanted to do it this week, got distracted trying to automate the release, and never finished. @virtualtam thank you v much if you find a moment to do it. There is also 5bd62b5d538a5e375bebbcdea0ffef3384143895 to cherry-pick

**Comment by ArthurHoaro** [comment]
Thank you for taking the time to release the fix @virtualtam !

**Comment by anmol26s** [comment]
@virtualtam 
I apologise for my post. I understand its difficult to keep upto date with these type of threads.
Thanks for the update.

**Comment by virtualtam** [comment]
You're welcome, thanks for understanding our position as fellow maintainers :)
