### ISSUE TITLE
pinned shaares do not sort alphabetically

### ISSUE THREAD

**Issue by kaergel** [shaarli/Shaarli#1289]
Hi,
currently pinned shaares sort by creation-time, which is kind of annoying. I think it would be usefull to be able to choose if pinned shaares are sorted by time or alphabetically.

Best regards

**Comment by ArthurHoaro** [comment]
I don't really see the point of sorting shaares alphabetically. IMO it's a feature which would add unnecessary complexity.

**Comment by ArthurHoaro** [comment]
Closing regarding my last comment. Feel free to comment with additional use cases if you think this feature should be added.

**Comment by Manja-S** [comment]
I already wrote [here](https://github.com/shaarli/Shaarli/issues/73#issuecomment-523985253)
"I'd like to add my vote to this request. Ideally I would like to be able to switch easily between alphabetical and date-based sorting in any screen (e.g. list filtered by tags) that shows links."

An alphabetical list gives me the possibility of a quick scan/overview of all of the links I've got (or I've got with a specific tag). To me searching/filtering doesn't give the same overview (and possibility for [serendipity](https://www.1843magazine.com/content/ideas/ian-leslie/search-serendipity)) that scanning a (sorted) list gives me. It gives me an opportunity to easily scroll to a link instead of having to click and type to apply a filter as well.
