### ISSUE TITLE
"Compact" link list view

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1328]
Sometimes I would like to see my links as a very condensed/compact list (for example something that looks like this:)

![Capture d’écran_2019-07-19_20-48-42](https://user-images.githubusercontent.com/3950390/61558192-e2787d00-aa55-11e9-9a24-43a083eb4c99.png)

This can be achieved by putting links lists, as markdown, in descriptions; but then you lose the benefit of each link having its own metadata, different tags, full-featured API interaction, etc.

It would not have to be a simple URL list like this sample. The format could be `$url - $title` + an icon to expand the entry and show full metadata/"large" display.

The advantage would be that you could see many links at a glance relevant to a specific search/tag.

Currently a "collapse" 
![Capture d’écran_2019-07-19_20-45-52](https://user-images.githubusercontent.com/3950390/61558045-77c74180-aa55-11e9-9422-0b2791441166.png) button exists that allows you so to minimize link height. But even with this mode toggled on, about 10 links are displayed on a 1080p screen; whereas the "compact" would allow you to see 40+. Maybe this could be made a "third" state of the collapse button.

You can pull the links via the API and display them in this fashion but it requires many steps.

**Comment by ArthurHoaro** [comment]
This is quite specific and it looks more like data manipulation than a feature to me. What about a simple CSV export?

Otherwise we can imagine a plugin which would display the links as your example in a modal?

**Comment by nodiscc** [comment]
This is more a layout "preference", but yes it would be cumbersome to have it enabled all the time.

`?do=taglist` is another example of a useful condensed layout (tag cloud has other uses, like discovery)


The main idea behind this, is that I still maintain flat, wiki-like bookmarks like [this](https://gitlab.com/nodiscc/NOTES/tree/master) - it's just a mirror of a personal gitea wiki. These bookmarks date back several years, they have been moved to/from Shaarli many times (extremely easy to do), but I keep coming back to flat file storage, mainly because of the compact view:

- Sometimes I just want to see all the available bookmarks on a topic at a glance, no pagination, reduced metadata, etc.
- Flat bookmarks are also easy to organize (only 2 levels - `topic.md` -> `# topic`) but that can probably be done with the right tagging system...
- Alphabetical sorting... I have to admit it helps with this use case (groups links by URL and I often mass-bookmark documentation sites). This was at https://github.com/shaarli/Shaarli/issues/73
- Markdown files are also readable offline, syncable through git. I'm still working on synchronization tools for Shaarli but it takes time.

I'd love to have all the possibilities offered by the API for each link (synchronization, search, metadata...). I'll try to move them back to Shaarli again, and use it in unexplored ways :) It never ceases to amaze me.

Something can probably be done with only CSS ("compact" stylesheet). I'll try that also and report back.

**Comment by Braintoe** [comment]
I also wanted a more compact view than the default Shaarli template provides (I use Shaarli in a side panel of Vivaldi), with at least 10...15 entries showing, regardless of their content. Therefore I fussed a little with the code of the default template:
 original:
![original template](https://user-images.githubusercontent.com/53839388/62582899-49978d80-b8ae-11e9-8a69-b269d726e277.jpg)

smaller version:
![smaller](https://user-images.githubusercontent.com/53839388/62582912-5320f580-b8ae-11e9-950c-33cddf8b6c8f.jpg)

I fear I am not able to contribute much due to lack of programming skills, but maybe this little bit might help for an intermediate solution for more information per screen unit.

Here is what I changed (caution, rusty html knowledge and not tested in detail, but apart from some minor things I did not find any problems yet):
- changed behaviour of descriptions to be invisible instead of being visible after load of the page
- moved timestamp and permalink into description area so they are not visible by default
- changed link title style to cut off long text instead of inserting line breaks. the smaller the window width gets, the more space is saved by that.
- reduced overall whitespace and font sizes
- changed to the [Assistant font](https://github.com/hafontia/Assistant/tree/master/Fonts/Webfont) that I subjectively feel to be a little more space efficient/easier to read in smaller sizes than the default.
Please find the detailed changes in the following files attached - feel free to ignore the colour changes, that's personal preference ;-).
[Comparison - shaarli-default-linklist-paging-html.pdf](https://github.com/shaarli/Shaarli/files/3474546/Comparison.-.shaarli-default-linklist-paging-html.pdf)
[Comparison - shaarli-default-linklist-html.pdf](https://github.com/shaarli/Shaarli/files/3474548/Comparison.-.shaarli-default-linklist-html.pdf)
[Comparison - shaarli-default-css.pdf](https://github.com/shaarli/Shaarli/files/3474549/Comparison.-.shaarli-default-css.pdf)

**Comment by dajare** [comment]
I would also love for there to be a "minimalist" theme for this "minimalist" bookmarking app (which I've been using for some years now). So far as I know, the most compact theme available — but now no longer updated for current Shaarli — is the "[2004licious Theme][1]:

![2004llicious](https://raw.githubusercontent.com/ManufacturaInd/shaarli-2004licious-theme/master/sample-screenshots/index.png)

Something that approximated the [Pinboard layout][2] would likewise be welcome:

![pinboard](https://pinboard.in/images/bookmark_example.png)

Do any theming experts know how much work it would take to update the 2004licious Theme for current use? Or whether it would form the basis for developing the kind of layout that OP is interested in?

[2]: https://pinboard.in/tour/
[1]: https://github.com/ManufacturaInd/shaarli-2004licious-theme

**Comment by toolleeo** [comment]
Agree with @nodiscc that this "issue" could be addressed by allowing an alternative layout for the presentation of links.

One single "line" per item would be enough, with title or URL, and optionally some "compact" data such as dates or tags. Bonus would be the possibility to configure the desired fields to be shown in the plugin configuration.

**Comment by ArthurHoaro** [comment]
I have another suggestion after switching to QHD screens, where the width is slightly ridiculous.
It's not exactly fixing the issue about a compact view, but what do you think about a grid view? 
Something similar with what we can have in the daily view, but more polished and full-featured.

![home](https://i.imgur.com/fDo1RIU.png)
![monthly](https://i.imgur.com/sw4CmPy.png)

**Comment by nodiscc** [comment]
A grid that adapts to screen width looks like a good way to go. I have always liked this simple but very good grid system: https://thisisdallas.github.io/Simple-Grid/ (https://github.com/ThisIsDallas/Simple-Grid). I think a layout based on this, using `col-1-1` (mobile), `col-1-2` (desktop) and `col-1-3` (wide/QHD) might be worth looking into.

**Comment by ArthurHoaro** [comment]
We are already using [PureCSS' grid](https://purecss.io/grids/) but we might need to extend it and/or use it better for wide screens.

**Comment by uraza** [comment]
I started using Shaarli recently and I also feel that each link is too "big" on the screen.
I second the idea of having a compact view: it could be similar to the way RSS readers usually display articles, with only the main information available (only the title?) until the entry is expanded.

**Comment by Ezyweb-uk** [comment]
If only there was a grid or kanban style layout. I really like the layout used by Qlearly.

**Comment by nodiscc** [comment]
Related https://github.com/shaarli/Shaarli/issues/1813 (Fold all shaares by default in link list view)

**Comment by nodiscc** [comment]
> This is quite specific and it looks more like data manipulation than a feature to me.

I finally came to the same conclusion and wrote tool to archive and manipulate Shaarli (and other) data: https://github.com/nodiscc/hecat. It is the successor to https://github.com/nodiscc/shaarchiver and I updated the documentation there with examples of how to work with Shaarli data. If you want a compact link list view, you will be interested in the `exporters/html_table` processor:

![image](https://github.com/shaarli/Shaarli/assets/3950390/c4b08479-5657-4f2a-9930-6eb3a05ced6a)

There is still work to do to make it more usable, and add more features (a "clean" page archiving capability implementation for example) https://github.com/nodiscc/hecat/issues?q=is%3Aissue+is%3Aopen+shaarli. But it is already working well, I've been using it for a few months to have a portable export of my Shaarli, and archive bookmarked video/audio

**Comment by dajare** [comment]
It seems that there is now a new option for a "compact" view theme for Shaarli: I've just run across ["Shaarli Stack" theme by RolandTi](https://github.com/RolandTi/shaarli-stack). It plays very nicely with both the "default colours" plugin, and my `data/user.css` mods. It is (at the moment!) being actively developed, and works great with Shaarli v. 0.12.2. :)

If only there was an **up-to-date** list of *working* Shaarli themes - it would make things like this easier to find!

**Comment by RolandTi** [comment]
> it is (at the moment!) being actively developed, and works great with Shaarli v. 0.12.2. :)
 
Thanks ! As I use Shaarli everyday, I will continue to update Stack.

**Comment by nodiscc** [comment]
In my opinion this is fixed by the https://github.com/RolandTi/shaarli-stack theme, and alternatively https://github.com/nodiscc/hecat.

Let's close this.
