### ISSUE TITLE
Issues with the release make target

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#1335]
I had 2 issues with the `release_archive` make target I did not have before. I changed my dev environment, so I'm not sure if it's due to my configuration or not.

#### `htmldoc`

> error: invalid command 'bdist_wheel'

I had to run `pip install wheel` before installing mkdoc (https://stackoverflow.com/a/44862371/1484919). I don't really know python tools so I'm not sure what was going on here.

#### `release_zip`

The command `mkdir -p $(ARCHIVE_PREFIX)/{doc,vendor}` while running make wouldn't create the directories properly.

```shell
mkdir -p Shaarli/{doc,vendor}
rsync -a doc/html/ Shaarli/doc/html/
rsync: mkdir "<path>/Shaarli/Shaarli/doc/html" failed: No such file or directory (2)
make: *** [Makefile:126: release_zip] Error 11

$ ll Shaarli
total 4,0K
drwxrwxr-x 2 arthur arthur 4,0K juil. 27 12:14 {doc,vendor}
```

However running the command directly from my zsh, it was working properly. Maybe I'm missing some dev package...

**Comment by virtualtam** [comment]
> error: invalid command 'bdist_wheel'

This usually happens when using a virtualenv with outdated versions of `pip` and `setuptools`, I've seen this recently on Debian Stretch hosts with Python 3.5 virtualenvs. An easy workaround is to pin a minimum version of `pip` to be used by the virtualenv.

> mkdir -p $(ARCHIVE_PREFIX)/{doc,vendor}

This could happen if the path expansion `{doc,vendor}` fails, e.g. when using `sh` as the SHELL interpreter. Maybe we should enforce Bash usage in the Makefile?

Reference:
- https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

Surprisingly, this has been set in the `v0.8.7` release but doesn't appear in the `master` branch: https://github.com/shaarli/Shaarli/blob/v0.8.7/Makefile#L14

**Comment by ArthurHoaro** [comment]
> This usually happens when using a virtualenv with outdated versions of pip and setuptools

It looks like installing my distribution's `setuptools` package fixed the issue.

> Surprisingly, this has been set in the v0.8.7 release but doesn't appear in the master branch

This change fixes the issue. :)
But it looks like this set of changes never made it to the `master` branch (at least partially, I'm not sure): #1156
