### ISSUE TITLE
batch "add multiple links" feature

### ISSUE THREAD

**Issue by s1dh** [shaarli/Shaarli#137]
When we use one browser's window per topic search, it could be handy to save all the tabs in that window with the same tags in shaarli (like Command + Shift + D in Chrome osx version e.g.)

Of course , and as it hsas been said in others issues, copy/paste tags is possible for each tab we want to bookmark, but I found that way quite overkill.

**Comment by nodiscc** [comment]
The way I see it there's no way to add a browser-wide shortcut for this because it's outside Shaarli's scope (how could it know about your open tabs?).

It was proposed in https://github.com/shaarli/Shaarli/issues/115#issuecomment-75490331 to make the `Add link` dialog URL input field multi-line (`<textarea>`), and add each line as a separate link. So the workflow would go like:

 * Open the `Add link` dialog (`/?do=addlink`)
 * Save all your tabs to a browser bookmarks folder and copy/paste the folder ([screenshot](https://cloud.githubusercontent.com/assets/3950390/6482426/08ae2308-c266-11e4-9ac0-3fbe9f62704c.png)) to the `Add link` field **or** copy URLs one-by-one to the `Add link` field
 * Click the `Add link` button.
 * You are sent to an `Edit link` dialog (`?do=editlink`) for the first URL you entered, where you are able to edit the title, description, private/public flag, tags...
 * Click `Save` to validate
 * You are sent to an `Edit link` dialog for the second URL **which retains the tags you entered for the previous one**.
 * Clicking `Save` sends you to the `Edit link` dialog for the next URL, and retains the tags you just entered, and so on...

Quick visual overview of the workflow:
![2015-03-04-note-12-31](https://cloud.githubusercontent.com/assets/3950390/6482833/bafeed9a-c26a-11e4-94cd-c83f93b2f5a1.png)

**Comment by s1dh** [comment]
Sorry for being too much naive , while reading to this : https://stackoverflow.com/questions/11114395/get-urls-of-all-open-tabs-in-chrome-and-send-it-to-a-web-service

I thought it was possible to know the url of all open tabs in javascript (maybe it depends of the browser ).

Your workflow is a way "longer" that detecting all open tabs but it is quite better than the actual workflow (copy/paste) I have.

**Comment by nodiscc** [comment]
https://stackoverflow.com/questions/6553334/how-to-get-the-url-of-currently-opened-tabs-in-all-browsers-with-php-or-javascri

> You can't, this information is just not available via any standard interface (except for a window you already have a reference to). You can see why. You wouldn't want the site owner for one of your tabs to be able to know what all your other tabs were showing, that would be a massive invasion of your privacy.

**Comment by ArthurHoaro** [comment]
Your workflow seems rather complicated to accomplish @nodiscc. What about a textarea with one URL per line, with default tags and private status for all of them ; then users can eventually edit the description if they want to?

**Comment by nicolasdanelon** [comment]
@nodiscc if you click the cancel button you are canceling that link. You should add a new button for cancel all. what do you think about that?
@ArthurHoaro what about a new accordion view? like this [one](https://jqueryui.com/resources/demos/accordion/default.html) of course we can do it with out jquery
every "section" in the example will be a "add link" form. in php we'll have a foreach and then ready. we can add all the links. theoretically.

**Comment by nodiscc** [comment]
@ArthurHoaro You are both right, @nicolasdanelon's solution looks better:

 * Single textearea supporting one URL per line + a global `tags` and `private` setting
 * Click `OK` -> Show a page with several `Edit link` dialogs/divs, one for each submitted URL; for each one the `Title` field is prefilled as per the page title, and `tags` and `Private` status are prefilled as per the global setting chosen before.
 * Edit individual links (or not), click `Save all`
 * An accordion/collapsing view would be a nice extra
 * Page title requests could benefit from being done in parallel (else the operation might take a long time when adding many links)

**Comment by ArthurHoaro** [comment]
I agree, this would be a nice feature. However, I'm pushing the milestone since this would be easier to take down with the bunch of refactoring/improvements planed for the next versions.
