### ISSUE TITLE
How to add/use extra php variables in templates

### ISSUE THREAD

**Issue by mfioretti** [shaarli/Shaarli#1370]
Hello, and sorry for the probably confusing subject, here is what I actually need help with:

I want to add, right after the edit icon under each bookmark listing, a link to a local copy of the same page, archived with other software.

looking at the source code, I have discovered that I can do this by changing this string of code into the linklist.html template:

`<a href="?edit_link={$value.id}" title="{$strEdit}"><i class="fa fa-pencil-square-o edit-link"></i></a>`

in this way:

`<a href="?edit_link={$value.id}" title="{$strEdit}"><i class="fa fa-pencil-square-o edit-link"></i></a><a href="http://shaarli.example.com/webarchive/{$value.id}/" title="local archive target="_blank" >local archive</a>`

This works as expected (but if there is a better/cleaner way to do it, please let me know!). If the shaarli ID number of a bookmark is, say, 234, I **DO** get a working link to

`http://shaarli.example.com/webarchive/234/` 

The problem is that, for several reason, I would **really, really** need that link to have this format:

`http://shaarli.example.com/webarchive/00234/` 

That is the number should be fixed length, left-padded with zeroes. As I understand it, this means I should have something like `webarchive/{$value.zeropaddedid}`, instead of  `webarchive/{$value.id}` in the patch above. And this is my problem. I *believe* I should add a line like:

`$value['zeropaddedid'] = str_pad($value['id'], 5,'0', STR_PAD_LEFT);`

somewhere in the code, but even if I am right, I confess I do not know PHP well enough to figure out where exactly I should do it, so I'm asking here.

Thanks in advance for every help, I'd really need to patch shaarli this way!

**Comment by ArthurHoaro** [comment]
Instead of directly editing the template file, I strongly suggest that you create a plugin. It'll be way easier to maintain and you won't have issue upgrading your Shaarli. You will be able to manipulate PHP code in your plugin.

You can take a look at:
  
  * existing [archiveorg](https://github.com/shaarli/Shaarli/tree/master/plugins/archiveorg) and [qrcode](https://github.com/shaarli/Shaarli/tree/master/plugins/qrcode) plugins which are similar with what you're trying to achieve (adding a link on every bookmark depending on its data
  * [plugin system documentation](https://shaarli.readthedocs.io/en/master/Plugin-System/)

Otherwise I think you can call a function in the template engine with 

```
{function="str_pad($value.id, 5,'0', STR_PAD_LEFT)"}
```

**Comment by ArthurHoaro** [comment]
I'm glad I could help you.

Be careful though, unfortunately we use an old version of RainTPL. I don't know the difference but the reference would be https://github.com/feulf/raintpl/wiki/Documentation-for-web-designers
