### ISSUE TITLE
[Feature Request] Tag docker images with version and latest

### ISSUE THREAD

**Issue by lonix1** [shaarli/Shaarli#1453]
The latest image does not have a version tag. (I'm confused about the difference between the `latest`, `master` and `stable` branches, but in any case, they do not have version tags.)

This is not standard practice, because you will always pull the latest version, and have no control over versioning. In most environments the infrastructure is tested in development, then tested in staging, then deployed to production. So one "pins" the version to be used, because one knows "it works". If we use `latest` (or master, stable, etc.), then it will pull a new version automatically, and it might break something. Pinning versions allows us to be sure what is deployed is 100% working as tested.

So please consider doing this:
- Add *version tags*. For example, if the latest version is `1.2.3` then the image should be tagged as `1.2.3` *as well as* with the `latest` tag.
- The true "latest" docker image by convention must be tagged as `latest`, because that is what docker will pull (whereas it looks like on docker hub the latest image is actually "master").

Thanks!

**Comment by nodiscc** [comment]
I am currently reworking the documentation in https://github.com/shaarli/Shaarli/pull/1389 (almost done) which includes a proposed change in branches/release model. In the proposed model

- each git `tag` would have a corresponding Shaarli docker image with the same tag (eg `shaarli:0.90.0`
- the `stable` branch/image is removed
- the `release` branch/image is the last tagged/released version (currently named `latest`)
- the `master` branch has a generates a docker image tagged `shaarli:latest` instead of master, as the convention dictates

Small example history graph:


Advantages: simpler to maintain and understand, follows convention (the latest release is considered stable, development docker image is tagged latest. It scraps the "stable" tag wich was really the `oldstable` release)

I can update the tooling accordingly if @virtualtam and  @ArthurHoaro are OK with the proposed changes.

**Comment by lonix1** [comment]
Yes that is excellent!

I'm not sure how to prevent the breaking change you mentioned. 😞

**Comment by lonix1** [comment]
A workaround in the meantime is to use the image digest.

So to get the "latest" image, with version pinning,

instead of: `shaarli/shaarli:master`

use: `shaarli/shaarli@sha256:cbcaf471281f05a7568f522c69d1c1d670336426774b991d67587a75c3b22a5f`

**Comment by nodiscc** [comment]
Following the merge of https://github.com/shaarli/Shaarli/pull/1389, to enable what we discussed, we should do the following:
 - [ ] Configure the https://hub.docker.com/ Shaarli account to autobuild images on git tags
  - @ArthurHoaro do you have the Dockerhub credentials for the account?
  - We might-have to force-push tags to trigger the builds...
 - [ ] Delete the `stable` branch/tag
  - [ ] this should be noted in the next version release notes, people who have been using the `stable` branch/image will no longer receive updates, and should switch to the `release` branch/image
 - [ ] Configure the dockerhub account to build an image tagged `:latest` for pushes on the master branch
  - [ ] also worth a mention in release notes, people who have been using the `:latest` release image will now receive images built from master, and should switch to the `release` image
 - Rename the `latest` branch to `release`

**Comment by ArthurHoaro** [comment]
> Configure the hub.docker.com Shaarli account to autobuild images on git tags 

I don't understand the issue here, tag builds seem to be already available:

![](https://i.imgur.com/v6ANe2G.png)

> @ArthurHoaro do you have the Dockerhub credentials for the account?

Yes, I am in the shaarli team but you don't seem to be. Do you want me to add you?

> Rename the latest branch to release

Good call. When we chose this terminology for our branches, we weren't aware that `latest` was kind of a for Docker to be the latest image *available*.

**Comment by nodiscc** [comment]
> https://hub.docker.com/u/nodiscc
> also confirm that this is you

yes this is me

> Do you want me to add you

please

**Comment by ArthurHoaro** [comment]
You should now have full access.

**Comment by nodiscc** [comment]
- [ ] Configure https://hub.docker.com/repository/docker/shaarli/shaarli/builds/edit to build `latest` image from the `master` branch
- [ ] Delete old `master` image tags

**Comment by nodiscc** [comment]
Fixed and clarified in current `master` and since the [0.12.2](https://github.com/shaarli/Shaarli/releases/tag/v0.12.2) release:
- The latest image built from `master` is now tagged `latest` [[1]](https://github.com/shaarli/Shaarli/pkgs/container/shaarli/79142816?tag=latest)
- The image tagged `master` has been deleted
- Images for each release have the same tag as the git tag (e.g [`ghcr.io/shaarli/shaarli:v0.12.2`](https://github.com/shaarli/Shaarli/pkgs/container/shaarli/78397072?tag=v0.12.2) built from git tag [`v0.12.2`](https://github.com/shaarli/Shaarli/tags))
- The image tagged [`release`](https://github.com/shaarli/Shaarli/pkgs/container/shaarli/78776449?tag=release) image is built from the `release` git branch to which the latest git tag (`v0.12.2` currently) has been merged (they do not have the exact same digest because they are actually built from different branches)
- The image tagged [`v0.12`](https://github.com/shaarli/Shaarli/pkgs/container/shaarli/78396307?tag=v0.12) is built from the `v0.12` git branch to which the latest `v0.12.x` git tag has been merged
- The image tagged `stable` has just been removed, please use `release` instead.
