### ISSUE TITLE
Disable help pages unless logged in

### ISSUE THREAD

**Issue by lonix1** [shaarli/Shaarli#1460]
Users who are not logged in can still access the help pages:
`https://shaarli.example.com/doc/html/index.html`

I realise this is just redirecting to another site, but it appears *on our domain*.

If I turn on the privacy options, nothing should be possible for users who are not logged in.

How can this be disabled?

**Comment by nodiscc** [comment]
> this is just redirecting to another site, but it appears on our domain

It's not redirecting, a copy of help pages is actually hosted on your own server (depending on the installation method used - [release](https://github.com/shaarli/Shaarli/releases) archives *do* contain a copy of the docs), so that you don't rely on the website for documentation.

> If I turn on the privacy options, nothing should be possible for users who are not logged in.

This is just static HTML documentation, and outside the control of Shaarli's authentication mechanism.

> How can this be disabled?

You can either remove completely the `doc/` directory, or configure your webserver to deny access to these pages. Which method would you prefer? (so that I can include it in the [ongoing](https://github.com/shaarli/Shaarli/pull/1389) documentation rework)

**Comment by lonix1** [comment]
@nodiscc Thanks for the detailed explanation.

Hmm... This is a tough one.

My first inclination is to block it in nginx. But the problem with that is it will block it even for me, even when I'm logged in.

The idea to delete the `docs/` directory has the same problem.

On the other hand, if auth doesn't cover static files, then there is no other way. So unless this is changed at the app level, I guess the easiest option for most users is just to delete the files.

**Comment by ArthurHoaro** [comment]
I'm closing this issue as we do not plan to handle documentation access at application level.

As you mentioned, you can safely delete the docs folder. You can also remove the footer links to the docs, or change it to the online one https://shaarli.readthedocs.io/en/master/.
