### ISSUE TITLE
Show Add Link field on home page when logged in

### ISSUE THREAD

**Issue by e2jk** [shaarli/Shaarli#147]
Enhancement suggestion: When logged in, show the Add URL field right on the home page. The form directs to the same page as when adding the link from the regular "Add Link" page, so no special form submit code is needed.

When I want to add a new link, this is my current workflow:
1. Go to my web page
2. Click Log In (as I'm often not logged in anymore, due to e.g. other computer/device)
3. Submit login form, redirected to the home page
4. click Add Link
5. Paste new URL

If the home page had the form right away, step 4 would not be needed.

The field should be discrete. How about adding it after the Search and Filter by tag fields?

**Comment by nodiscc** [comment]
I'd not like a 3rd field there very much. The UI is already far from perfect with only 2 fields. I also  rarely use `Add Link`. A few comments:

 * Is there any particular reason why you don't use the bookmarklet (general question about workflow)?
 * Your solution saves exactly 0 clicks. Step 4 you'd have to find, point and click the "Add link" field (instead of the button).
 * You could save a bookmark to `?do=addlink` in your browser bar, or make use of your browser's autocompletion? (Eg. after some time, just typing `a` `TAB` `ENTER` would enter the dialog)
 * The add link field could appear in a dropdown instead of a separate page if you like this solution. But it also saves 0 clicks.
 * You could do minimal changes to the `new-plugin-system` branch and implement this as a a plugin. Add the possibility to inject items in the search bar [like I did here for the <head>](https://github.com/shaarli/Shaarli/commit/7da12bf6ab87da783d6a454a83545f0430e145bb); and add your field to eg. `tpl/plugins/addlinkfield/addlinkfield.searchbar.html`. Is the process of creating this clear enough?

**Comment by ArthurHoaro** [comment]
Fixed by #279.
