### ISSUE TITLE
Beta version: links export token refresh issue

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1532]
In the version v0.12.0-beta, I noticed that the CSRF token was added to the form that exports links.

But since the export proposes the HTML file to download without actually reloading the page, if you export twice, the second time you have a `Wrong token` error.

**Steps to reproduce**

- Go on export page
- Click the *Export* button
- Click the *Export* button again

You should see the error.

Not sure what is the best way to fix this. Maybe by regenerating a token after each click, or by forcing a full page reload after the export.

**Comment by ArthurHoaro** [comment]
Thanks for the report. I have opened a PR to fix this by regenerating the token on submit, as you suggested. 
We can't reload the page to achieve this, because the browser is technically on another page at this point (the URL serving the file), even though it's not visible. That's probably why a lot of tools open download link in a new tab.
