### ISSUE TITLE
problem upgrading from 0.11 to 0.12

### ISSUE THREAD

**Issue by ilPeo** [shaarli/Shaarli#1598]
I install from the zip release file, unpack and then move the old data folder back in place.
It keeps complaining that my datastore has been upgraded, then it shows a blank pahe whatever I do

`Your data store has been migrated, please reload the page. If this message keeps showing up, please delete data/updates.txt file.`

**Comment by ArthurHoaro** [comment]
Hi,

If you have a blank page you probably have an error logged in your web server logs.

**Comment by ilPeo** [comment]
> Hi, If you have a blank page you probably have an error logged in your web server logs.

yes, it has:
`[17/Oct/2020:05:43:23 -0700] "GET /Shaarli/ HTTP/2.0" 302 214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0"`

**Comment by nodiscc** [comment]
> yes, it has:

This is the access log, nothing to see here. Your webserver should have a separate `error.log` file with the actual error message.

**Comment by ilPeo** [comment]
I had actually looked in `error.log` but i found it empty.
In the meanwhile I managed to have my Shaarli instance back by deleting my config file from `\data`and recreate the same user again.
The first time it complained about the datastore to be migrated, then everything was back in place.
Maybe my config file was corrupted? I tried comparing it with the new one but didn't find any clue.
Thanks

**Comment by averymd** [comment]
I ran into similar behavior during the upgrade on the day 0.12.0 was released and had to roll back to the previous version. Despite an empty page loading, no errors showed in the `error.log` file. I couldn't find any Shaarli-specific logs to determine what might be happening. Manually increasing the PHP error log levels using `error_reporting()` high in `index.php` didn't reveal anything, either.  Attempting to run the php files on the CLI results in errors due to missing HTTP headers, which is unsurprising. (I didn't log the issue here because I couldn't find enough info to be helpful.)

Is there another way I can get data to help with diagnosing this? I also suspect the issue has to do with my config file, as I was able to get an instance running by letting it be recreated, but I don't want to recreate my settings and that probably shouldn't be necessary for anything less than a major version upgrade.  😄 If it would help, I can provide a redacted version of my config file.

The changelog notes that the markdown plugin is removed, but I still see markdown referenced in the documentation--should it have been removed from my config file? I tried removing it myself, but that didn't resolve the issue.

**Comment by ArthurHoaro** [comment]
> If it would help, I can provide a redacted version of my config file.

That would be great, thanks.

> The changelog notes that the markdown plugin is removed, but I still see markdown referenced in the documentation--should it have been removed from my config file? I tried removing it myself, but that didn't resolve the issue.

Plugin loading is supposed to be fail safe, so I don't think that's the issue, BUT markdown should have been automatically removed from your plugins list during the update. So I suspect something went wrong, but I'm not sure what, yet.

**Comment by averymd** [comment]
The config files were long, so I put them in a gist: https://gist.github.com/averymd/6815849bd10c0df61a3ee0de7ff50ab4

The 0.12.0 config is from after the second load: first load gives the "data store updated, if this keeps appearing, delete updates.txt" message, second load is blank, and that's when I grabbed the config file.

Maybe also worth noting is that after the update, I have two data store files, the second containing a timestamp in the filename.

**Comment by ArthurHoaro** [comment]
Thank you! I was able to reproduce the issue. There are two actually:

  - With latest release material theme (not compatible with v0.12.0), so was generating errors.
  - Shaarli tried to display the error using the template engine... which is where the error comes from.
  - Then with the master branch, I had a blank page without an error once, then cleared the `tmp/` cache and it's now working (at least displaying something, I can't compile assets for some reason). 

I'll submit a PR to at least display an error message if an exception is thrown in the error handler.

**Comment by averymd** [comment]
I should have thought to disable the theme. 🤦 I switched off the theme in 0.11.1, and the upgrade went smoothly (no blank screen, no need to clear `/tmp`).

**Comment by ArthurHoaro** [comment]
No worries! Glad I could help.

@ilPeo Does it fix your issue?

**Comment by ilPeo** [comment]
Maybe, as I already told you I fixed by creating a new config file (I had the material theme too), so I guess that’s the solution.
Thx

**Comment by ArthurHoaro** [comment]
OK so it was probably the same issue. Thanks!

**Comment by virtadpt** [comment]
Same problem here (v0.11.1 to v0.12.1), same fix.
