### ISSUE TITLE
Changes in Travis CI pricing 

### ISSUE THREAD

**Issue by immanuelfodor** [shaarli/Shaarli#1649]
Hi Everyone,

I've just learnt that Travis CI is making changes to their pricing model that affects OSS projects, too. You might want to look into this depending on your usage stats: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

The original article that linked to the above post in the first paragraph: https://blog.healthchecks.io/2020/11/using-github-actions-to-run-django-tests/

> I recently found out Travis CI is ending its free-for-opensource offering, and looked at the alternatives.

**Comment by immanuelfodor** [comment]
More articles: 
- https://ropensci.org/technotes/2020/11/19/moving-away-travis/
- https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
- https://medium.com/dictcp/how-travis-ci-kills-the-productivity-of-a-100-team-in-2-hours-9e66ed275f5a

This is not great news, I really hope you don't have to rewrite the entire build automation of Shaarli.

**Comment by ArthurHoaro** [comment]
Thanks for the report, I saw a few emails from Travis but I missed that it was affecting all OSS projects. 

We have some time to work on it before consuming all free tier 10k credits, but we should probably move to another provider. It means that we will have to rewrite the CI configuration, but with our Docker image and Makefile, it will be fairly easy to do.

Regarding other CI providers, I don't have experience with a lot of different ones - I used CircleCI and GitLab-CI (self-hosted) - but Github Actions seems to become popular and I suppose it can fit our needs.

**Comment by immanuelfodor** [comment]
I'm using a self-hosted Drone CI, and they are also free for OSS in their cloud option: 
- Cloud build: https://cloud.drone.io/
- Plugins: http://plugins.drone.io/
- Docs: https://docs.drone.io/
- Example config for Docker build in one of my projects: https://github.com/immanuelfodor/kube-karp/blob/master/.drone.yml

I've found the Drone config to be more compact and plugin oriented than Gitlab CI, but Github Actions for a Github project seems to be a perfect match :) See also https://github.com/shaarli/Shaarli/issues/1555#issuecomment-714679613

**Comment by nodiscc** [comment]
> we will have to rewrite the CI configuration
> Regarding other CI providers,
> CircleCI and GitLab-CI
> Github Actions
> Drone CI

I use Gitlab CI (both SaaS and self-hosted, multiple instances), it is extremely [full-featured](https://docs.gitlab.com/ce/ci/yaml/README.html) and Free software. However it needs pairing with a Gitlab instance (which is possible via our [gitlab.com mirror](https://gitlab.com/shaarli/Shaarli) - by the way mirroring is [stuck](https://forum.gitlab.com/t/mirroring-error-commit-graph-chain-lock-exists/38518) by an error which requires manual admin intervention - I sent a support request). It would make sense to investigate a FOSS and relatively portable and reusable solution. For example https://framagit.org/ maintains a public Gitlab instance with Gitlab CI enabled. 

I have started looking into Drone to link with a self-hosted Gitea instance. Pipeline configuration looks simple and featureful. It is probably the most portable solution - I thought it required self-hosting, didn't know about the SaaS offering. Requirements are quite simple (although am not conviced by running the CI service/master itself in Docker /nightmares of [docker-in-docker](https://hub.docker.com/_/docker/) builds in gitlab ci - it is written in Go so supposedly should work as a single binary, but build instructions are a bit lacking).

There are [other CI systems](https://github.com/ligurio/awesome-ci).

Github Actions is becoming popular and seems to be on par with Travis features, as a project hosted on github.com (almost) I suppose it would make sense to use it despite its proprietary/SaaS-only nature. It's also probably the path of least effort to [this](https://github.com/shaarli/Shaarli/issues/1555).

In the mean time we can keep using Travis - there is no global counter on https://travis-ci.com/github/shaarli/Shaarli but I don't think we hit the ~1000 hours limit. Performance problems explained in the blog post might explain why I've been getting very long build times (+1hr in preparing state). Credit is due to them, they have been providing free builds for a long while to tons of projects.

> Docker image and Makefile, it will be fairly easy to do

Indeed, and a good argument to keep as much automation as possible in the Makefile, making the project relatively independent from the CI system. Rewriting the pipeline to any of those we mentioned is probably not much work.

What do you think?
Would be good to have this before [1.0.0](https://github.com/shaarli/Shaarli/milestone/4) ?

**Comment by ArthurHoaro** [comment]
Drone seems to fit our use case in its features and free SaaS version: https://www.drone.io/enterprise/opensource/#features

I think that Github Action might be more reliable in the long term, but that's a subjective opinion. Also as you mentioned with #1555, it's probably more integrated with... Github.

In any case, I'd rather avoid using a self-hosted solution due to the maintenance it requires over time.

> Would be good to have this before 1.0.0 ?

Sure, and before we consume all free credits.

**Comment by denis-ev** [comment]
FYI
This is how I do the docker publishing via GitHub Actions and Semantic-Releases etc.
https://github.com/VivumLab/VivumLab/tree/dev/.github/workflows

**Comment by nodiscc** [comment]
Drone CI pipeline prototype at https://github.com/nodiscc/Shaarli/pull/4 (I implemented two crude php7.4 and 7.3 test pipelines, both are giving out different errors). Advice welcome
