### ISSUE TITLE
Port/server config problems

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#17]
Here is a summary of problems related to specific server/network configs:

* ~~https://github.com/sebsauvage/Shaarli/issues/101: RSS feed has an incorrect url _-- waiting for info_~~  **fixed**
* ~~https://github.com/sebsauvage/Shaarli/issues/108: next and the previous day of my shaarli dont work _-- waiting for info_~~  **no reply, closed**
* https://github.com/sebsauvage/Shaarli/issues/110: ~~Lost oasis bug~~ **closed, added to the wiki**
* ~~https://github.com/sebsauvage/Shaarli/issues/132: Shaarli behind an apache proxy _-- waiting for info_~~ **no reply, closed, fixed**
* ~~https://github.com/sebsauvage/Shaarli/issues/164: Add log of last 10 logins~~ **done. login attempts are stored in data/log.txt**
* ~~https://github.com/sebsauvage/Shaarli/issues/172: https redirect with htaccess~~ **likely not a Shaarli bug. waiting for info**
* ~~https://github.com/sebsauvage/Shaarli/issues/181: Shaarli not able to write in its folder~~ **moved to https://github.com/shaarli/Shaarli/issues/40**
* ~~https://github.com/sebsauvage/Shaarli/issues/180: ATOM does not work on reverse proxy~~ **Fixed**
* ~~https://github.com/sebsauvage/Shaarli/issues/183: No login possible while using port forwarding (no standard-port~~ **no reply, closed**
* ~~https://github.com/sebsauvage/Shaarli/issues/186: Strange login behaviour _-- waiting for info_~~ **no reply, closed**
* ~~https://github.com/sebsauvage/Shaarli/issues/196: Cookies not working on localhost: redirect to 127.0.0.1~~ **fixed**

**Comment by ArthurHoaro** [comment]
I found this issue after switching PHP builtin server to port 8080 and see this: 

![snapshot2](https://cloud.githubusercontent.com/assets/1962678/5677846/f6a50a68-97eb-11e4-9603-106ec95d8597.png)

As [this guy said](http://stackoverflow.com/a/2297421), relying on `SERVER_NAME` instead of `HTTP_HOST` is better. That's partially what sebsauvage#165 did, and it solves my issue.

Then I took the time to setup an instance behind a reverse proxy, and I couldn't reproduce any of the issue @nodiscc listed. See here (login: root - azerty):

 * Reversed: https://tmpreverse.hoa.ro
 * Direct: https://tmplinks.hoa.ro:8443

It'll be up while you guys review the following PR.

**Comment by nodiscc** [comment]
Thanks for investigatin the problem @ArthurHoaro, your PR seems to fix all reverse proxy problems. I'm glad to see all listed issues are closed; I'll now close this tracker bug. I'm still waiting for info on https://github.com/shaarli/Shaarli/issues/79.

Thanks again!
