### ISSUE TITLE
Permalink issue

### ISSUE THREAD

**Issue by oblab** [shaarli/Shaarli#1749]
I just don't understand why there is duplicate urls for permalink, example :
https://mydomain.com/shaare/O0PLRQ and https://mydomain.com/?O0PLRQ

It's in includes.html file, there is a meta property : `<meta property="og:url" content="{$index_url}?{$link.shorturl}" />`
and in daily.html file : `<a href="{$base_path}/?{$link.shorturl}" title="{'Permalink'|t}">`

Shouldn't this be : `<meta property="og:url" content="{$index_url}shaare/{$link.shorturl}" />` ?

**Comment by ArthurHoaro** [comment]
`mydomain.com/?O0PLRQ` are the old URL format which has been replaced by `mydomain.com/shaare/O0PLRQ`.

Both are still valid because we did not want to break existing permalinks.
However you are right, all permalinks should use the `/shaare` format in the templates. I must have forgotten one.

Would you mind sending us a PR?

**Comment by oblab** [comment]
done !

**Comment by ArthurHoaro** [comment]
Thank you for the report and fixing it!

**Comment by oblab** [comment]
done another change in the "vintage" template
