### ISSUE TITLE
Unable to delete tags with many shaares from tag list (timeout)

### ISSUE THREAD

**Issue by github-account1111** [shaarli/Shaarli#1854]
When I click the trashcan icon for any tag, it take a 20-30 seconds, then the tag disappears, then upon a page refresh it's there again.

**Comment by nodiscc** [comment]
Please post the [installation](https://shaarli.readthedocs.io/en/master/Installation/) method you used, shaarli version, as well as any relevant configuratino file or error logs from your server.

**Comment by github-account1111** [comment]
I used the Docker installation method.
I haven't edited the config file.

All I've done is import all my bookmarks and synchronize all the thumbnails.

I'm actually not sure how to access server logs, was wondering myself and couldn't find it in the docs.

**Comment by github-account1111** [comment]
I've made a recording of the issue:

https://user-images.githubusercontent.com/5728319/164884476-5c993b3f-0b32-4768-a405-c8b1827f358e.mp4

**Comment by znoteer** [comment]
I can confirm this bug. I've tried removing both by clicking "Tools" in the top bar of the interface, choosing "Manage Tags", entering the name of the tag, then choosing delete, and using the delete icon in the list view of tags.

Could this be because there are still shaares with the tag? I hope not. I imported my bookmarks from Firefox. 

Every bookmark got the "Bookmarks" tag, and all bookmarks that were in the bookmarks toolbar got the "toolbar" tag. Those aren't useful tags and it's tedious to have to remove the tags from every shaare (I have over 3,500 bookmarks. While that may not be a lot compared to some people, that's still a lot of clicking to remove tags).

This was indirectly installed via the Freedombox (a pure blend of Debian) plinth interface. Under the hood it was installed via a Debian package. The shaarli interface footer tells me I'm running version 0.12.1

I don't see anything obvious in journalctl. The only errors in which the regex "haar" appears are like the following

`apache-error[1177]: [Sat Oct 08 07:13:49.581282 2022] [proxy_fcgi:error] [pid 1190:tid 2811655200] [client 192.168.1.185:48494] AH01071: Got error 'PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/shaarli/application/helper/FileUtils.php on line 49', referer: https://<servername>/shaarli/tags/list?sort=alpha`

and

`apache-error[6919]: [Sun Oct 09 10:57:00.105970 2022] [proxy_fcgi:error] [pid 6923:tid 2870404128] [client 192.168.1.185:34828] AH01071: Got error 'PHP message: Failed to retrieve https://raw.githubusercontent.com/shaarli/Shaarli/latest/shaarli_version.php', referer: https://<servername>/shaarli/login`

neither of which look likely to be related to me.

**Comment by nodiscc** [comment]
> I imported my bookmarks from Firefox.
> Every bookmark got the "Bookmarks" tag
> shaarli-remove-tags-mute.mp4: bookmarks 3042

That could help reproducing this bug. @znoteer how many bookmarks did you import this way?

I've never tried untagging so many bookmarks at once, that is probably the reason.

> PHP Fatal error: Maximum execution time of 30 seconds exceeded

A possible workaround is to increase the max execution time in the php-fpm pool configuration `/etc/php/*/fpm/pool.d/`. I have mine set to 30s as well [[1]](https://github.com/nodiscc/xsrv/blob/master/roles/shaarli/templates/etc_php_PHPVERSION_fpm_pool.d_shaarli.conf.j2#L32) [[2]](https://github.com/nodiscc/xsrv/blob/master/roles/shaarli/defaults/main.yml#L40). 

> Those aren't useful tags and it's tedious to have to remove the tags from every shaare

It could be useful to know which bookmarks come from a browser import. But then the tag should be `imported` or something explicit, not `bookmarks`. Can be reported in a separate issue.

> all bookmarks that were in the bookmarks toolbar got the "toolbar" tag

This is because folder names are converted to tags during import, so this is the normal/expected behavior.

**Comment by znoteer** [comment]
On Sun, Oct 09, 2022 at 12:05:04PM -0700, nodiscc wrote:
> > I imported my bookmarks from Firefox.
> > Every bookmark got the "Bookmarks" tag
> > shaarli-remove-tags-mute.mp4: bookmarks 3042
> 
> That could help reproducing this bug. @znoteer how many bookmarks did you import this way?

I don't remember the exact number and I've removed some bookmarks since the import, but it was around 3,500 of which approxiamately 1100 were also tagged "toolbar".

> 
> I've never tried untagging so many bookmarks at once, that is probably the reason.
> 
> > PHP Fatal error: Maximum execution time of 30 seconds exceeded
> 
> A possible workaround is to increase the max execution time in the php-fpm pool configuration `/etc/php/*/fpm/pool.d/`. I have mine set to 30s as well [[1]](https://github.com/nodiscc/xsrv/blob/master/roles/shaarli/templates/etc_php_PHPVERSION_fpm_pool.d_shaarli.conf.j2#L32) [[2]](https://github.com/nodiscc/xsrv/blob/master/roles/shaarli/defaults/main.yml#L40). 

I've max_execution_time in /etc/php/7.4/{cli|fpm}/php.ini but not in the www.conf file which is the only file in /etc/php/7.{3|4}/fpm/pool.d Is it the php.ini files you meant?

**Comment by znoteer** [comment]
I tried changing the value of max_execution_time from 30 to 300 in both 

- /etc/php/7.4/cli/php.ini and 
- /etc/php/7.4/fpm/php.ini 

to no avail. The error message still mentions a 30 second max. 

I had a look at your example files, and I don't appear to have a "main.yml" on my freedombox in either /etc or /usr/share, so I can't change the  `shaarli_php_max_execution_time` from that file. 

Any ideas about where else I might find those 30 seconds being defined?

**Comment by nodiscc** [comment]
> Any ideas about where else I might find those 30 seconds being defined?

- Figure out where your php-fpm service loads its configuration from:

```bash
$ systemctl show php7.4-fpm.service |grep ExecStart=
ExecStart={ path=/usr/sbin/php-fpm7.4 ; argv[]=/usr/sbin/php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf ; ignore_errors=no ; start_time=[Mon 2022-10-10 00:53:22 CEST] ; stop_time=[n/a] ; pid=526 ; code=(null) ; status=0/0 }
```

- Verify the current value of `max_execution_time` set by the current config:

```bash
$ sudo php-fpm7.4 --fpm-config /etc/php/7.4/fpm/php-fpm.conf -tt 2>&1|grep max_execution_time
[11-Oct-2022 18:17:55] NOTICE: 	php_admin_value[max_execution_time] = 30
```


- In `/etc/php/7.4/fpm/php-fpm.conf`, there is no mention of `max_execution_time`, but the last line says to load configuration from files in `/etc/php/7.4/fpm/pool.d/*.conf`:

```bash
$ tail -n1 /etc/php/7.4/fpm/php-fpm.conf
include=/etc/php/7.4/fpm/pool.d/*.conf
```


- List files in this directory:

```bash
$ ls /etc/php/7.4/fpm/pool.d/
ldap-account-manager.conf  nextcloud.conf  shaarli.conf  tt-rss.conf  www.conf
```

(ignore extra files in my example, by default only the `www.conf` pool is present, I just configured a different pool for each application on my server).

- Set `php_admin_value[max_execution_time] = 300` in `/etc/php/7.4/fpm/pool.d/www.conf`
- Verify that the configuration is correctly seen by php-fpm:

```bash
$ sudo php-fpm7.4 --fpm-config /etc/php/7.4/fpm/php-fpm.conf -tt 2>&1|grep max_execution_time
[11-Oct-2022 18:18:55] NOTICE: 	php_admin_value[max_execution_time] = 300
```

Restart the php7.4-fpm service to reload the config:

```bash
$ sudo systemctl restart php7.4-fpm.service
```

**Comment by znoteer** [comment]
I spoke too soon. I am unable to remove the "bookmark" tag. There are 1,009 shaares thus tagged. I get the 504 Gateway Timeout error as above and the tag is not removed from any shaare.

**Comment by nodiscc** [comment]
> 504 Gateway Timeout

This time it's apache timing out waiting for a reply from php-fpm. The default is [60 seconds](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxytimeout)

> Removing the tag one shaare at a time was very tedious

You could have used the [API client](https://github.com/shaarli/python-shaarli-client) and [`DELETE /tags/bookmark`](https://shaarli.github.io/api-documentation/#links-tag-delete) (would be interesting to see if it runs into timeouts and how long it takes). But anyway the operation is supposed to work in the Shaarli UI, it's just that it was never timed.

- [ ] We could add a section about this in https://shaarli.readthedocs.io/en/master/Troubleshooting/, as importing a large amount of browser bookmarks is likely to be used by many users.
- [ ] The "bug" could also be reported against the Freedombox/Debian package [[1]](https://tracker.debian.org/pkg/shaarli) to see if they could add a php-fpm/apache configuration snippet that works around this by default? (ping @jvalleroy)
- [ ] Remains the question of Docker images as originally reported by OP/@github-account1111. A workaround could be documented (or increase timeouts by default?)

**Comment by znoteer** [comment]
`ls /etc/apache2/sites-enabled`

lists two sites: `freedombox-default.conf` and `<fqdn>.conf`

Neither file returns anything in answer to `grep ProxyTimeout`.

The two conf files above are actually softlinks to same named files in `../sites-available`. In this dir, in addition to the above files, there are `000-default.conf`,  `default-ssl.conf` and `default-tls.conf`. `grep ProxyTimeout` didn't get anything back from them either.

I'll wait to hear from jvalleroy before deciding whether to report this on the FBX issue tracker.

**Comment by jvalleroy** [comment]
> `ls /etc/apache2/sites-enabled`
> 
> lists two sites: `freedombox-default.conf` and `<fqdn>.conf`

I think we can specify a ProxyTimeout in freedombox-default.conf. [The file](https://salsa.debian.org/freedombox-team/freedombox/-/blob/master/data/etc/apache2/sites-available/freedombox-default.conf) is maintained in the FreedomBox repository.

Since ProxyTimeout is not set anywhere, it falls back to the value of Timeout from `/etc/apache2/apache2.conf` (set to 300). @znoteer Please open an issue on Salsa FreedomBox project for adding ProxyTimeout.

**Comment by znoteer** [comment]
I created a [ticket](https://salsa.debian.org/freedombox-team/freedombox/-/issues/2291) on the FBX issue tracker.

https://salsa.debian.org/freedombox-team/freedombox/-/issues/2291

**Comment by znoteer** [comment]
I left a comment about my experience changing the values of `php_admin_value[max_execution_time]` and `ProxyTimeout` on the [freedombox issue tracker](https://salsa.debian.org/freedombox-team/freedombox/-/issues/2291#note_343198).

In short, I tried setting these values to 300 which timed out and then to 1200 which succeeded in deleting a tag appearing in 1009 shaares.
