### ISSUE TITLE
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by lionneye** [shaarli/Shaarli#1859]
Bonjour,

Sans récent changement à mon shaarli en hébergement mutualisé, j'ai commencé à voir s'afficher une popup avec le message "An error occurred. Return code: 405", popup récurrente quand je suis sur la page principale de mes liens depuis cette semaine.

Quand j'ouvre la console du navigateur je vois
"Failed to load resource: the server responded with a status of 405 (Method Not Allowed)"
/shaarli/admin/shaare/1837/update-thumbnail:1

Shaarli version **0.12.1**
Serveur web PHP **8.0** (j'ai essayé avec 7.4 mais le problème persiste)

J'ai regardé les problèmes déjà traités, j'ai trouvé [#1674](https://github.com/shaarli/Shaarli/issues/1674) mais je n'arrive pas à appliquer les recommandations, surtout que je ne suis pas dans un contexte d'upgrade.

Voyant que le problème semble lié aux miniatures, j'ai essayé de vider le cache "clear thumbnails cache" mais la synchronisation ne se fait pas avec le même message d'erreur 405.
J'ai aussi vidé le cache de mon navigateur et le problème persiste.

Je suis allée voir les logs d'erreur du webserveur, il y a seulement ça
[mutu11124] [Sat Jun 18 13:30:54.791400 2022] [php:error] [pid 19727] [client 91.170.22.142:0] Failed to retrieve https://raw.githubusercontent.com/shaarli/Shaarli/latest/shaarli_version.php, referer: https://jlionne.com/shaarli/admin/shaare/1509

J'ai une utilisation basique de shaarli et une faible maîtrise de la gestion du serveur web où je l'ai hébergé. Je le gère seulement par le biais de FTP par Filezilla. Je n'utilise pas de console pour le gérer.

Merci par avance pour votre aide. 

Jessica

**Comment by nodiscc** [comment]
Hi,

See https://shaarli.readthedocs.io/en/master/Troubleshooting/ -> `Error 406 "Not acceptable"` and https://github.com/shaarli/Shaarli/issues/1838 https://github.com/shaarli/Shaarli/issues/1662 https://github.com/shaarli/Shaarli/issues/1838 (other symptoms of the same problem).

Your shared hosting provider prevents outgoing HTTP requests from the server, which are required for shaarli to grab metadata/thumbnails from remote pages. Your hosting provider's control panel may allow disabling this restriction, otherwise you could ask them to lift the restriction through their support channel.

You may also disable thumbnails completely to prevent this error from happening.
