### ISSUE TITLE
Error: datefmt_create: No such time zone: 'Europe/Kyiv': U_ILLEGAL_ARGUMENT_ERROR

### ISSUE THREAD

**Issue by andmizyk** [shaarli/Shaarli#1892]
Error
```
Error: datefmt_create: No such time zone: 'Europe/Kyiv': U_ILLEGAL_ARGUMENT_ERROR
```
on page Daily when the timezone is chosen 'Kyiv'
Shaarli version 0.12.1

```
        datefmt_create: No such time zone: 'Europe/Kyiv': U_ILLEGAL_ARGUMENT_ERROR
/usr/share/shaarli/application/Utils.php324
#0 /usr/share/shaarli/application/Utils.php(324): IntlDateFormatter->__construct()
#1 /usr/share/shaarli/application/helper/DailyPageHelper.php(180): format_date()
#2 /usr/share/shaarli/application/front/controller/visitor/DailyController.php(35): Shaarli\Helper\DailyPageHelper::getDescriptionByType()
#3 [internal function]: Shaarli\Front\Controller\Visitor\DailyController->index()
#4 /usr/share/php/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#5 /usr/share/php/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /usr/share/shaarli/application/front/ShaarliMiddleware.php(55): Slim\Route->__invoke()
#7 [internal function]: Shaarli\Front\ShaarliMiddleware->__invoke()
#8 /usr/share/php/Slim/DeferredCallable.php(57): call_user_func_array()
#9 [internal function]: Slim\DeferredCallable->__invoke()
#10 /usr/share/php/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#11 /usr/share/php/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}()
#12 /usr/share/php/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#13 /usr/share/php/Slim/App.php(503): Slim\Route->run()
#14 /usr/share/php/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke()
#15 /usr/share/php/Slim/App.php(392): Slim\App->callMiddlewareStack()
#16 /usr/share/php/Slim/App.php(297): Slim\App->process()
#17 /usr/share/shaarli/index.php(176): Slim\App->run()
#18 {main}
```

**Comment by nodiscc** [comment]
Hi,
I cannot reproduce the problem on my install (shaarli 0.12.1 from [release zip](https://shaarli.readthedocs.io/en/master/Installation/#from-release-zip) on Debian 11, PHP 7.4). The Daily page displays normally regardless of the selected time zone. 

In my case the dropdown list shows `Kiev`, not `Kyiv`. This reflects the timezones available on my system:

![image](https://user-images.githubusercontent.com/3950390/192343774-6a768f18-b9a9-4bb0-8604-d01793747856.png)
```
$ timedatectl list-timezones|grep -E 'Kyiv|Kiev'
Europe/Kiev
```

- Is it listed as `Kyiv` for you in the dropdown list?
- How did you install shaarli (source/composer, release zip, other...)?
- What is your OS and PHP version?

(There seems to have been a change in spelling in the PHP timezone list earlier this year, see [[1]](https://github.com/php/doc-en/issues/1319) [[2]](https://www.php.net/manual/en/timezones.europe.php)).

I could not test on https://demo.shaarli.org/ as the config is read-only.

**Comment by nodiscc** [comment]
Can you please show the output of 

```
apt-cache policy tzdata | grep Installed
php -i | grep -i timezone
php -v
```

**Comment by nodiscc** [comment]
I think the problem lies there:

- your tzada 2022c-1 package has `Europe/Kyiv` since it was added in version [2022b-1](https://metadata.ftp-master.debian.org/changelogs//main/t/tzdata/tzdata_2022c-1_changelog) (that's what, I guess causes `Europe/Kyiv` to display in the dropdown menu?)
- but your PHP 8.1.5 does not have `Europe/Kyiv` in [it's internal database](https://raw.githubusercontent.com/php/php-src/php-8.1.5/ext/date/lib/timezonedb.h) yet. 

If (?) this is correct, it's not a problem specific to shaarli but would affect any PHP application on your system.

These kind of out-of sync situations tend to happen when running [Debian Testing](https://wiki.debian.org/DebianTesting), which is one of the reasons why I would advise against it (on a server at least). It is not Debian 12 until Debian 12 (stable) has been released ;) In addition Testing has the worst security fix response time when compared to stable or unstable.

I suggest either:
- waiting for an update of your PHP packages to version that contains the updated db (it may take some time, the db was updated on [August 11](https://github.com/php/php-src/commits/master/ext/date/lib/timezonedb.h), there has been no releases since, and even Debian unstable is still on [8.1.7](https://tracker.debian.org/pkg/php8.1), 3 versions behind). You may want to report the problem on the Debian bug tracker but I think it will solve "itself" as the PHP packaging team packages new releases.
- ~~switching to Debian unstable~~ it's affected too.
- consider switching back to stable+backports (not possible without full reinstall unfortunately).

ping @jvalleroy who maintains the Debian package.

In the mean time you should be able to select `Europe/Kiev` in the dropdown and the application should work.

**Comment by andmizyk** [comment]
At the moment, I solve this problem for myself by switching to another city in the same time zone, like Athens. 
So I'll wait when 8.1.10+ will appear in debian. Thanks.

**Comment by nodiscc** [comment]
That also works. Take care
