### ISSUE TITLE
Unraid PHP Fatal Error

### ISSUE THREAD

**Issue by mlause** [shaarli/Shaarli#1904]
Hi,

I installed Shaarli as a docker in unraid. I'm getting this error. The webui is blank.

2022/10/22 18:30:03 [error] 11#11: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The file could not be opened. Check permissions. in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php:134
Stack trace:

What could the issue be?

**Comment by nodiscc** [comment]
>  installed Shaarli as a docker in unraid.

Please post the complete installation steps and relevant logs.

**Comment by ChonLee** [comment]
I had the same issue and I was able to solve this by going into the console of the container and running chown -R 100:101 /var/www

**Comment by nodiscc** [comment]
@mlause does the workaround above fix your problem?

**Comment by legovaer** [comment]
I can confirm that the workaround fixes the issue. A nice solution would be having to be able to specify UID and GID as an environment variable.

A good example: [entrypoint script from photoprism](https://github.com/photoprism/photoprism/blob/develop/scripts/dist/entrypoint.sh)

**Comment by ArthurHoaro** [comment]
This is a simple permission issue: Shaarli needs to be able to write in the `data` folder through the server user/group to work properly. See [Installation > Set File Permissions](https://shaarli.readthedocs.io/en/master/Installation/#set-file-permissions)

However, it would be nicer to handle this error gracefully and land on the server page instead of a fatal error.
