### ISSUE TITLE
No thumbnails on shared hosting

### ISSUE THREAD

**Issue by cborne** [shaarli/Shaarli#1979]
Bonjour, 
j'ai un shaarli dans la dernière version installée v0.12.2 sur un serveur mutualisé chez o2switch. 
Tout fonctionne normalement sauf la génération des miniatures. Le compteur reste bloqué à 0. 
Je suis dans une version 8.1 de php, tous les indicateurs sont au vert. 
Je ne sais pas quelles informations je peux donner de plus. L'adresse est ici : https://news.restez-curieux.ovh/
Merci

**Comment by nodiscc** [comment]
Hi,

(please use English so that everyone can benefit from this issue - https://www.deepl.com/translator gives good results if you are not comfortable writing in English, merci d'avance)

- Make sure thumbnails are enabled for `all` hosts in the [configuration](https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#thumbnails). By default thumbnails are only generated for some hosts like youtube.com, vimeo.com... [[1]](https://github.com/shaarli/Shaarli/blob/master/application/Thumbnailer.php#L16)

If this still doesn't work:

- Your shared hosting provider may have disabled downloading of external files by the server (see https://github.com/shaarli/Shaarli/issues/1859 https://github.com/shaarli/Shaarli/issues/1838) - in that case check your **server logs** if they are available, you should see errors related to that. Contact your hosting provider support.
- Your hosting provider may have a security system in place which blocks thumbnail generation requests (see https://github.com/shaarli/Shaarli/issues/1662), in that case you should get an error code (probably `406`, `403`) in your **browser console**. Contact your hosting provider support.

**Comment by cborne** [comment]
Hi thanks for your answer. In o2switch, it's "TigerProtect" the security system wich blocks generation thumbnails.
It works now.
