### ISSUE TITLE
user.css in data directory has no effect (shared hosting)

### ISSUE THREAD

**Issue by aegidius77** [shaarli/Shaarli#1986]
Hi,

Copying this ```user.css``` file in shaarli v0.12.1 ```/data``` directory has no effect :

[https://github.com/simon-mettler/shaarli-theme](https://github.com/simon-mettler/shaarli-theme)

Did I miss something ?

**Comment by nodiscc** [comment]
It works for me as documented in https://shaarli.readthedocs.io/en/master/dev/Theming/#custom-css **however** you need to make sure that both `data/user.css` and `data/.htaccess` are readable by the webserver user (commonly `www-data`).

@aegidius77 do you get errors in your browser console, such as `GET https://shaarli.example.org/data/user.css [HTTP/2 403 Forbidden]`?

What are the owner/group/permissions on `data/`, `data/.htaccess`, `data/user.css`?

Note: I got an unrelated error `The resource from “https://shaarli.example.org/data/user.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).` - this was caused by my custom server configuration (`Header always set X-Content-Type-Options "nosniff"` in `/etc/apache2/conf-available/security.conf`), after commenting out this directive, this error is gone. But we should double-check the recommended config to ensure that the correct mimetype is sent.

**Comment by aegidius77** [comment]
Hi,

Thank you and sorry for late replying.

Permissions are :
```
- data : 755
- data/.htaccess : 644
- data/user.css : 644
```
Here are GET requests results :
```
GET
http://...shaarli/
[HTTP/1.1 200 OK 308ms]

GET
http://...shaarli/plugins/qrcode/qrcode.png
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/data/user.css
[HTTP/1.1 302 Found 0ms]

GET
http://...shaarli/plugins/qrcode/shaarli-qrcode.js
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/plugins/playvideos/jquery-1.11.2.min.js
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/plugins/playvideos/youtube_playlist.js
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/plugins/code_coloration/prism.js
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/tpl/default/js/shaarli.min.js?v=3945e963005dd1451024aa7e569ba2a96ec198358f0604e983be7d6687cf1417
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/tpl/default/js/thumbnails.min.js?v=3945e963005dd1451024aa7e569ba2a96ec198358f0604e983be7d6687cf1417
[HTTP/1.1 200 OK 0ms]

GET
http://...shaarli/tpl/default/js/metadata.min.js?v=3945e963005dd1451024aa7e569ba2a96ec198358f0604e983be7d6687cf1417
[HTTP/1.1 200 OK 0ms]

GET
https://errors.infinityfree.net/errors/403/

GET
http://...shaarli/tpl/default/img/apple-touch-icon.png

GET
http://...shaarli/tpl/default/img/favicon.png


```

**Comment by nodiscc** [comment]
> - data : 755
> - data/.htaccess : 644
> - data/user.css : 644

These permissions look correct, the webserver should be able to read .htaccess and user.css without problem. So the problem must be elsewhere.

> GET
> http://...shaarli/data/user.css
> [HTTP/1.1 302 Found 0ms]

HTTP 302 indicates a redirect, which URL does this request redirect to?

**Comment by nodiscc** [comment]
> `Location: https://errors.infinityfree.net/errors/403/`

It seems to redirect to your hosting provider's 403 Forbidden error page.

Have you checked this? https://forum.infinityfree.com/t/redirected-to-infinityfree-403-forbidden-page/58664

**Comment by aegidius77** [comment]
> > `Location: https://errors.infinityfree.net/errors/403/`
> 
> It seems to redirect to your hosting provider's 403 Forbidden error page.
> 
> Have you checked this? https://forum.infinityfree.com/t/redirected-to-infinityfree-403-forbidden-page/58664

Hi,
I've just made another test to see if, by any chance, things could have been changed since my last test. And it's eventually working as expected. Something must have been changed server side by my hosting provider's since my last test, but I don't know what exactly ...
So no more problem here for now.
Thanks for your support

**Comment by aegidius77** [comment]
> **Edit :**
> 
> However, still have the issue on a Synology local web server :
> 
> ```
> GET
> http://xxx.xxx.xxx.xxx/shaarli/data/user.css
> [HTTP/1.1 403 Forbidden 3ms]
> ```

Hi,

.htaccess file in data directory seems to be involved : as a test, renaming it to _.htaccess  made 403 error disappear. Renaming it back to .htaccess makes 403 error back again.
