### ISSUE TITLE
About the "branding" of this fork opposite legacy Shaarli

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#203]
About the "branding" of this fork, maybe it is time to be more clear to make the difference between this fork and the "legacy" version of Sebsauvage? We could try to find another name something about "Community Shaarli" Or Shaarli2 (shaarli too/two)? ... or not if Sebsauvage migrate or merge his github project to this fork (who know?).

Before to make this kind of change we could yet be more clear into the current readme. I suggest to begin (just after the logo) by  _**Community friendly fork** of Shaarli, the personal, minimalist, super-fast, no-database delicious clone_ as i did on http://shaarlidemo.tuxfamily.org/

In same time, you can also change the tagline of the project with the same mention (the current mention _- community repo _, at the end, is not visible enough.

Maybe we can do the same in the footer.

**Comment by qwertygc** [comment]
:+1:

**Comment by rubykat** [comment]
Agreed, this is a good idea. It's too confusing otherwise. I think it's more feasible to rename this Shaarli to something else than it is to ask Sebsauvage to take action - not because he wouldn't want to, but because he's too busy (which is the reason this fork happened in the first place).

An irreverent part of me wants a new logo which is a combination of the old logo and a picture of a fork. (Shaarli Fork, get it?) ;-) With a motto saying "now we can eat cake!" (okay that is even sillier)

**Comment by nodiscc** [comment]
The current changes from upstream are still very minor and it's fully mergeable. The upgrade path still works. I'm ok to change the project name/style/branding (this was proposed from the beginning), but I'd rather wait until we have more substantial changes. It should be done before 1.0 though. Sorry for the lack of updates, not much time these days.

**Comment by ParoTheParrot** [comment]
+1

**Comment by ArthurHoaro** [comment]
We now have substantial changes, and this is known as the « official » repo. @sebsauvage has added a link to this repo in his readme. Also, the description has been slightly changed recently. I feel like that's good enough.

Feel free to reopen if you think other changes should be made on this matter.
