### ISSUE TITLE
[doc] recommend a proper Free Software HTTP referer cleaner

### ISSUE THREAD

**Issue by Draky50110** [shaarli/Shaarli#209]
Salut

J'aime bien le principe de anonym.to mais j'aime moins le fait qu'il doit à mon avis garder une trace des sources...
Du coup, j'ai cherché une solution "auto-hébergée", histoire de rester VRAIMENT anonyme.

J'ai trouvé ça : https://stackoverflow.com/questions/6428762/hide-referrer-on-click
Sauf que ça ne marche pas, notamment en testant avec ça : http://www.whatismyreferer.com/

Du coup je suis tombé sur ça : http://sourceforge.net/projects/noreferplz/
C'est mort (site de l'auteur HS, Github vide, etc.) mais téléchargeable sur SF et installable.
Et ça marche, on a bien un système auto-hébergé avec construction de l'URL en www.site.com/anonym/?www.liens_shaarli.com et pas de referer !

Bref, est-ce envisageable d'inclure ce genre de script dans Shaarli, histoire d'avoir un équivalent "sûr" de anonym.to ?
Le script que j'ai cité est avec du .JS, du CSS, etc. mais ce n'est peut-être pas la peine de tout garder ?
Après, c'est peut-être indispensable d'avoir un vidage du referer en JS ET en PHP ?

Voilà.

**Comment by nodiscc** [comment]
Hi, thanks for your suggestion.

In my very humble opinion users should take care of masking their referrers using addons such as [Smart Referer](https://addons.mozilla.org/en-us/firefox/addon/smart-referer/) or their browser's preferences anyway (In firefox `network.http.sendRefererHeader=2; network.http.referer.spoofSource=2`). Keep in mind that if your Shaarli is accessed over HTTPS, browsers won't send reeferers to plain HTTP sites.

**But**, this looks like a simple way to mask referers directly in Shaarli :http://stackoverflow.com/a/11249553 (also look at the next answer, full PHP solution: http://stackoverflow.com/a/9026324). I wouldn't like to use the norefplz code because it's too complex for that simple task, but if someone can propose a patch to add an optional, simple (see above) referer blocking feature to Shaarli (replacing the current anonym.to solution), I would merge it. Please send Pull Requests because I won't work on this myself (I spoof all referers, except when staying on the same domain)

**Comment by nodiscc** [comment]
Or, we could just recommend a separate, self-hostable referer stripping program that is compatible with Shaarli. Just install it and point the anonymizer URL to it.

**Comment by Draky50110** [comment]
It is what I've done : have installer NoReferPLZ on my webhost and use it in my Shaarli's install...

**Comment by nodiscc** [comment]
If someone wants to cleanup the noreferplz code, and keep maintaining it (or write a new one from scratch, see 2 links above), we could recommend it in the doc and on the settings page.

**Comment by C-Duv** [comment]
A self-hosted code I am using (for other stuff than Shaarli) is the following PHP code:

```PHP
<!doctype html>
<html>
    <head>
        <title>Redirector hiding referer</title>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
        <meta name="robots" content="noindex,nofollow" />
        <meta name="referrer" content="no-referrer" />
    </head>
    <body>
<?php
if (isset($_GET['u']) && !empty($_GET['u'])):
?>
        <script>document.location = '<?php echo addslashes($_GET['u']); ?>';</script>
<?php
endif;
?>
    </body>
</html>
```

It uses JavaScript to change `document.location`.

**Comment by nodiscc** [comment]
I think this feature should be removed (and this issue closed), as the referer is now stripped when accessing a link to another domain: https://github.com/shaarli/Shaarli/pull/692

Note that this doesn't work on Chrome: https://github.com/shaarli/Shaarli/issues/720. Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=627968.

A workaround would be using the value `no-referrer` (but would break Shaarli redirection functionality relying on referers)

**Comment by ArthurHoaro** [comment]
I don't know. First, we've had multiple issues related to this feature, so at least a few people are using it. Also, having an intermediate redirection can be used for other things than just removing the referrer.

That being said, it makes the code more complex because anytime we manipulate an URL it depends on this settings, and also if the URL should be URL encoded ; for a feature that almost nobody use.

In any case, we can at least remove it from the settings in the UI.

**Comment by nodiscc** [comment]
> First, we've had multiple issues related to this feature, so at least a few people are using it.

Then maybe we should wait for https://bugs.chromium.org/p/chromium/issues/detail?id=627968 to be fixed. Would make this feature irrelevant in major browsers.

> having an intermediate redirection can be used for other things than just removing the referrer

True, but is there evidence of anyone using it this way?

> it makes the code more complex
> we've had multiple issues related to this
> we can at least remove it from the settings in the UI

:+1:

**Comment by nodiscc** [comment]
https://github.com/shaarli/Shaarli/issues/720 and https://bugs.chromium.org/p/chromium/issues/detail?id=627968 are now fixed, the referrer policy used by Shaarli is now supported in Chrome.

I suggest that the redirector code should be removed, will file a separate issue for this.
