### ISSUE TITLE
recipe for target 'code_sniffer_full' failed

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#300]
It's a bit strange (and very minor), but there is an error when I run code_sniffer goal:

```
$ make code_sniffer
[...]

Time: 1.59 secs; Memory: 40.5Mb

Makefile:45: recipe for target 'code_sniffer_full' failed
make: *** [code_sniffer_full] Error 1
```

code_sniffer actually works, but there is an error at the end for some reason... 

```
$ php -v
PHP 5.6.5 (cli) (built: Jan 22 2015 07:32:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by virtualtam** [comment]
This is due to being in a Makefile:
- each series of commands is spawned in a `sh` subprocess
- if the return code is different that 0, wich is the case for most CI tools if there's something dubious detected, then the `make` command will fail

To be sure, just check the return code of the executed command:
```bash
$ cd /path/to/shaarli
$ composer update
$ ./vendor/bin/phpcs [...]
$ echo $?
1
```

Given the status, convention-wise, of Shaarli, I agree it's a bit superfluous...

The nominal usage is to ease project maintainers' life, by having Travis reject PRs if conventions are violated: _code reviews should focus on code logic (interesting) instead of syntax parsing (mucho boring)_ :p

**Comment by ArthurHoaro** [comment]
Yep, phpcs returns 1 because errors/warnings. Doesn't matter. :)
