### ISSUE TITLE
Backup issues (to a separate branch) ?

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#302]
Should the project's repository contain a backup of code reviews/bug reports/discussion about the project?

Can be done with https://github.com/joeyh/github-backup (json) or https://github.com/nodiscc/scriptz/blob/master/dev/github-issues-backup.sh (markdown)

**Comment by virtualtam** [comment]
Not necessarily: issues are here mainly to discuss technical points, project-related topics and code reviews.

IMO, anything that is relevant to Shaarli, the server environment and the community should make its way to the Wiki (or code comments / README).

If we happen to have more activity from contributors and testers, it may be worth coupling an Agile board (e.g. [kanboard](http://kanboard.net/)) with GH Issues to have more control on:
- active tasks
- task effort/difficulty estimation
- task dependency

**Comment by nodiscc** [comment]
I was mainly concerned about  preventing data loss if something goes wrong with Github (see Sourceforge), and ensuring we were not too "locked-in" with Github tools; but you convicned me. Every relevant piece of the issues tracker should go to the wiki.

**Comment by virtualtam** [comment]
Well, project-specific issues usually have a very short lifespan, and may not contain a lot of information relevant for future uses.

What may be important though, is to keep track of the technical difficulties that have been tackled, and:
- encourage _clear, detailed commit messages_
- for 3rd party libs, upstream changes
- for implementation hacks, provide a clear documentation (README, wiki...)

That's why it's important to:
- keep commits atomic: 1 feature => 1 commit
- explain what is being added, modified or removed

When following these good practices, all information (in particular, deprecated or deleted stuff) can be retrieved from Git log and references; GitHub Issues, and, more generally, issue trackers, are merely convenience tools to encourage discussion and ease project management. :)
