### ISSUE TITLE
Shaarli does not recognize saved links

### ISSUE THREAD

**Issue by nicolasdanelon** [shaarli/Shaarli#325]
Hi, I'm running the shaarli version 0.5.1 and when I save a link shaarli does not have problems. But if I want to save the same link again shaarli does not load the tags.. issue here :(

**Comment by ArthurHoaro** [comment]
Confirmed.

**Comment by virtualtam** [comment]
I think it's related to #314 
More specifically, [`LinkDB->getLinkFromUrl`](https://github.com/shaarli/Shaarli/commit/d9d776af19fd0a191f82525991dafbb56e1bcfcb#diff-828e0013b8f3bc1bb22b4f57172b019dR1488) may not be too fond of being passed a `Url` object instead of a string.

In that case, the fix is to either:
- pass it a string object - `Url->__toString()`
- process `Url`s in `LinkDB` (could be saved for later, I'm not sure how much dev it implies)

**Comment by ArthurHoaro** [comment]
I chose the easy one. :)

**Comment by virtualtam** [comment]
Btw, it may be safer to do the casting in `index.php`, e.g.

```php
if (isset($_GET['post'])) {
    $parsed_url = new Url($_GET['post']);
    $url = $parsed_url->cleanup();
    [...]
```

**Comment by ArthurHoaro** [comment]
Yep, I changed that.

**Comment by nicolasdanelon** [comment]
Thanks for quick response and with all love and respect. What for is the test oriented development?

**Comment by virtualtam** [comment]
> What for is the test oriented development? 

@nicolasdanelon which dev are you referring to? :)

**Comment by nicolasdanelon** [comment]
@VirtualTam can u send me an email?

**Comment by nicolasdanelon** [comment]
@virtualtam shaarli.nicolasmd.com.ar we can test here. I've also see that youtube links does not have title. is this the same issue?

**Comment by virtualtam** [comment]
I think it's not related to Youtube, but rather to skipping page metadata retrieval if the URL scheme is not `http`, see [`index.php#1513`](https://github.com/shaarli/Shaarli/blob/master/index.php#L1513)
