### ISSUE TITLE
wrong  count items in tag cloud

### ISSUE THREAD

**Issue by emporeso2** [shaarli/Shaarli#363]
hi all,

i have a tag name "movies" that have no items but in the "Tag loud" tab i see "16 movies" ?

There is a way to clean  the Shaarli "database" ?

Thanks

**Comment by nodiscc** [comment]
@emporeso2 This is interesting. Do you have a tag `Movies` (or other uppercase/lowercase variation)? Did you clear your browser cache (or use `Ctrl+Alt+R` to refresh the tagcloud page)? Did you compare the results before and after restarting your webserver (might be server-side caching?).

Please let us know if you have more info

**Comment by emporeso2** [comment]
- I tested the browser cache : not this
- I restarted the browser : not this
- I can't acces the server configuration
- I rename the tag to the same name but nothing happen
- I delete the tag and it still appear in the tag cloud !

Maybe due to transfer from the orginal shaarli to this fork  (this what i did, i transfer the /data directory) ?

**Comment by nodiscc** [comment]
You could try this:

 * Export your shaarli bookmarks to HTML, logout
 * Delete data/datastore.php (this will delete all your bookmarks - **DO A BACKUP BEFOREHAND**)
 * Import back your bookmarks HTML export

Does this remove the non-existing tag?

Again, you should have a full backup of your Shaarli before trying this...

I would also try emptying the cache, tplcache and tmp directories.

Another possibility would be [debase64ing/deserializing](https://github.com/shaarli/Shaarli/wiki/Datastore-hacks#decode-datastore-content) your datastore and posting the output somewhere so that we can try to find what's causing this weird tag (if you don't have sensitive/private data in your datastore). I personally never had this problem.

**Comment by ArthurHoaro** [comment]
Any update here?

**Comment by ArthurHoaro** [comment]
Closing. Feel free to reopen it if you're still encountered your issue.
