### ISSUE TITLE
Error on 0.6.1.

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [shaarli/Shaarli#401]
I tried to update my Shaarli on 0.6.1 but there's an error on the bottom of page saying that newversion  from page.footer.... isn't defined. Is it normal?

**Comment by ArthurHoaro** [comment]
That's an issue we found out after releasing 0.6.1 and which is fixed by this commit 4a7af9759a1874bdf6ec00a286040a3c64b9870e. It will be shipped within v0.6.2.

However I suggest that you turn off [display-errors](http://php.net/manual/fr/errorfunc.configuration.php#ini.display-errors) in your `php.ini` if you're not using Shaarli for development purpose.

**Comment by ParoTheParrot** [comment]
Still here after update to 0.6.2
Notice: Undefined variable: newversion in /homepages/[MYHOMEPAGE]/shaarli/tmp/page.footer.5fe0cadbcd6454bbfe0631b4b83e1369.rtpl.php on line 8

**Comment by ArthurHoaro** [comment]
Can you try to clear your `tmp/` folder?

**Comment by alexisju** [comment]
Are you using another template than the default one ?

**Comment by ParoTheParrot** [comment]
I do use another template: https://github.com/kalvn/shaarli-blocks/

**Comment by alexisju** [comment]
@ParoTheParrot, the template you use seems not (yet) compatible with Shaarli 0.6.2, it is not a Shaarli's issue.

**Comment by ArthurHoaro** [comment]
Ping @kalvn

**Comment by kalvn** [comment]
Yep, as I mentioned, I stopped the development for this theme.

Although, as a quick fix, you can modify the file `blocks/page.footer.html` and replace `newversion` by `newversion` (with a uppercase V).

**Comment by ArthurHoaro** [comment]
Yep sorry, I thought this was your other one.
