### ISSUE TITLE
Only allow links access via permalinks

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#475]
Hello ! J'aime bien le [concept](https://n.survol.fr/n/une-page-daccueil-pour-un-site-semi-prive), et je voulais savoir si, quand on est pas connecté, il n'y pas la liste des liens, (il faut être abonné au RSS pour voir les articles ou avoir le permalien).

Si ça peut se faire sous forme de plugin... ?

**Comment by mro** [comment]
Hä?

**Comment by ArthurHoaro** [comment]
He's talking about a 'no homepage' option, for privacy matters. So no multiple link list if you're logged out.

**Comment by mro** [comment]
thx.

**Comment by alexisju** [comment]
I guess it should be possible, but i think it will be easier to use a custom template than a plugin for that.

**Comment by nodiscc** [comment]
I see this as an addition to "Hide public links".

 * All links are hidden
 * There is a RSS feed whose URL is generated randomly and bypasses "hide public links".
 * Accessing a permalink bypasses "hide public link"

**Comment by alexisju** [comment]
n.survol.fr (the website given in link by @qwertygc) is just a wordpress website "without" frontpage, but all articles are published and online. 

About Shaarli the same way is more like a specific template than a new core feature.

Hovewer, as @nodisc suggest, when the shaarli is private it could be interesting to be able to generate a private rss link too.

**Comment by ArthurHoaro** [comment]
I agree with @alexisju. A "featureless" template is a good way to make Shaarli only able to display permalinks.

Also, I'm more in favor of adding a 'share' URL to give access to a private link, or any link to make it work with `HIDE_PUBLIC_LINKS`. But it's going to be more difficult to do since we don't load private links for logged out users.

**Comment by qwertygc** [comment]
I have test the condition in linklist.html, but is hide, also if we search. I search just to hide for listing the links, not in search or tag ^^

**Comment by qwertygc** [comment]
I have create a pull request.

**Comment by ArthurHoaro** [comment]
What's the point of hiding shaares in linklist if you can see them through the search, tags, daily, etc?

**Comment by qwertygc** [comment]
L'idée c'est juste rendre plus opacte le shaarli, comme décrit dans l'article.

**Comment by ArthurHoaro** [comment]
Opaque? Hmm... The blog post author writes something like this:

> Yes, everything is accessible for anyone who would care to. Posts are browsable through pagination, RSS feed, or a search engine.
>
> I'm talking about opacity because it's not closed, only harder to access. It protects me against quick "who am I" search.

I'm sorry but it feels like a pointless hack to me. I'd rather hide everything and eventually make permalink accessible (like etherpad for example), or show everything that's public.

**Comment by nodiscc** [comment]
Agreed, if ever this gets implemented it needs to only allow access to RSS/permalinks and not allow listing of links; otherwise there is no point to it - just hide the default page.

@qwertygc what you describe can easily be done with a simple `.htaccess` or server access restrictions/configuration (throw a 403, 404 or a custom page for URLs like `^shaarli/\?` `^shaarli/\?page=.*$`, eg see [rewriterules](https://stackoverflow.com/questions/15877448/block-access-to-url-with-htaccess). I suggest closing https://github.com/shaarli/Shaarli/pull/478.

**Comment by qwertygc** [comment]
Si je comprends, on le met pas ?

**Comment by alexisju** [comment]
Perso, je ne pense pas non plus qu'il faille que ce soit intégré par défaut ; ça sort un peu de l'essence même de Shaarli. Par contre, n'hésite pas à développer ton template et le partager (en ajoutant un lien [dans le wiki](https://github.com/shaarli/Shaarli/wiki/Theming)).
