### ISSUE TITLE
Tags not sorted (fully) alphabetically without php-intl extension

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#530]
Some shared hosting providers dont enable the php-intl extension. This extension is currently required by Shaarli to sort tags (fully) alphabetically in the tags cloud. This could be an issue for some users in this circumstance.

For example, in french, tags beginning with special characters (é, è, î,...) remain at the end of the list in this case. Like :  A B C (...) X Y Z É È Î

_Shared hosting with php-intl_
OVH
Gandi  - http://phpinfo5-6.gandi-test.fr/
Infomaniak- http://imu330.infomaniak.ch/phpinfo.php
Online.net - http://demo.online.net/index.php
tuxfamilly http://hack.tuxfamily.org/phpinfo.php

_Shared hosting without  php-intl_
Ouvaton - https://ouvaton.coop/outils/
Lautre.net 
web4all.fr  https://php5-5.web4all.fr/
Free - http://perso129-g5.free.fr/php56/
lost-oasis.net - http://web.lost-oasis.net/5.3/index.php
domainepublic.net  - http://www.domainepublic.net/phpinfo.php
galacSYS.com - http://phpinfo.galacsys.com/
dreamhost.com - http://php56.dreamhosters.com/
all2all.org - http://www.all2all.org/fr/informations/faq/mysql-and-php/php5-modules-and-parameters/

**Comment by virtualtam** [comment]
Language-specific sorting is provided by PHP's [intl](http://php.net/manual/en/book.intl.php) extension, which is present in most installations (separate `php5-intl` package on Debian though).

Possible solutions:
1. shared hosting: see if administrators can install/enable the extension
2. dedicated hosting: install it ;-)
3. workaround: bundle Shaarli with a 3rd-party library

My grumpy cents: It is _truly astounding_, in 2016, to still stumble upon servers and software that are either not configured to properly support a locale other than `en_US` or `en_GB`, or re-invent the wheel by providing their own collation libraries instead of contributing to PHP's core and pushing system administrators towards doing their job properly O_o

**Comment by ArthurHoaro** [comment]
Adding a 3rd party lib would mean adding a bunch a dead code for most people. And it's a *very* minor issue IMHO.

So 4- Creating a third party plugin with one of these libs, which resort the taglist before tagcloud rendering.

**Comment by virtualtam** [comment]
@nodiscc wrote on Gitter:

> (investigating @virtualtam's suggestion 3. workaround: bundle Shaarli with a 3rd-party library in #530)

> hi all, does intl need to be compiled into php? or can it be 1. downloaded to a directory 2. have it manually imported and used by shaarli?

> I'm against workarounds to missing php extensions (is Shaarli going to workaround missing gd, mbstring also... - and it's a minor sorting bug) but if we can find a manual procedure or patch to fix it, why not?

This is somehow possible, yet terribly hack-ish. I did this while being a student to circumvent the university's limited Apache support. IMHO the time and skills required to achieve compiling a working PHP extension and deploying it locally are simply not worth it.

> 4- Creating a third party plugin with one of these libs, which re-sort the taglist before the tagcloud page rendering.

This is a bit better, but would force us to start introducing extra wrapper/abstraction layers and maintaining them. Looking at #324, I daresay it's not a path I'd wish to take ;-)

**Comment by ArthurHoaro** [comment]
@virtualtam you missed third party. :)

Closing since it won't be handle in Shaarli repo.
