### ISSUE TITLE
Opt-in or opt-out for rivers

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#584]
I have... concerns about what we call "Shaarli Rivers".  

You install shaarli on your server for what it is (sharing links) but in the same time you are now participating in a (proto-) social network without asking if you want it or not. I know that when you share something in public you have to accept some consequences but the rivers are different, because you didn't ask to participate and people want you to respond (I have 2 hate mails because I "ignore" them...).
It's not a website like a "planet-" or a "Hacker News", but, to me, it's a bad social network (even if it was not the idea). It's not about sharing links anymore but it's about debates and conflicts.

Is it possible to have an option in Shaarli asking if you want to participate or not?
Example: If I say "no", Shaarli will block the rivers based on a list.
(it's easy to block websites on a server but I don't know if it's possible to do that with Shaarli directly)

What do you think?

**Comment by ArthurHoaro** [comment]
> You install shaarli on your server for what it is (sharing links) but in the same time you are now participating in a (proto-) social network without asking if you want it or not.

No. Someone added you manually in the meantime.

> Is it possible to have an option in Shaarli asking if you want to participate or not?

Rivers are no more than 3rd party RSS syndication tools. IMHO there is nothing Shaarli *should* do about it directly, because it shouldn't have specific rules for specific syndicators.

If one doesn't want his feed to appear in those rivers, their is a few options:

  * ask to get removed,
  * block rivers server IP,
  * in a more automatic way, add a feature to ignore a Shaarli instance if [...]¹ in the rivers themselves. The only problem you got here is that the original river author is gone, I host a fork, @Oros42 hosts another fork, there is shaarli.fr which is another tool, etc.

So my vote goes to won't fix.

¹ A specific file if found, or anything.

**Comment by Oros42** [comment]
Same like @ArthurHoaro

Okay you have 2 hate mails but on how many people have read you ?
Hater's mails is a problem of communication and not of shaarli or 3rd party like river.

I can add a message in top of my river to explain why people could «ignore» a question (because they didn't read it).
I don't know how to write it. 

If you want to block a river, you can block the user-agent «shaarli-api-client». But for me, blocking a river or shaarlo, is not the solution to stop haters.

**Comment by daks** [comment]
Hello,
I'm new to shaarli and this issue raises questions to me that I want to understand.
When I install Shaarli with no 3rd party plugin, with default options, is my instance connected to others? does my instance 'ping' other instances and get referenced somewhere?
Thanks.

**Comment by Oros42** [comment]
@daks this is the list of shaarli use by my river : https://github.com/Oros42/shaarlis_list
 This list is update only by request of shaarli's user and not by using Google.

**Comment by daks** [comment]
okay, thanks.

**Comment by NerosTie** [comment]
@ArthurHoaro @Oros42 Thanks for your answers and I think you are right. I want to add that I'm not against the idea of rivers but against how some people use them. I don't say I'm an angel and I've made mistakes, even recently. Plus your rivers are simple (I like the dark theme btw), but not shaarlo, there is a real idea of a social network behind this one.

There are approx. 300 flux now and, let's face it, a lot of tension. In the future we will be more and it will be more and more a battlefield.  
What I'm trying to do is to find solutions to prevent it. Maybe blocking rivers is too extreme, I agree, maybe my ideas are not the right ones or maybe there is no solution at all... ¯\_(ツ)_/¯

@ArthurHoaro feel free to close it, it's not really an issue but more a discussion about how Shaarli is used in third-party tools.

**Comment by Oros42** [comment]
@NerosTie I think we should talk with all shaarli about how to manage tension. It's an old problem.
(Talk not here ^_^ but by shaarli or XMPP)
