### ISSUE TITLE
Make use of 404 template?

### ISSUE THREAD

**Issue by k0nsl** [shaarli/Shaarli#602]
I'm wondering if anyone is working on actually making use of the `404.html` template in the `tpl` directory. This could and probably should  be used for when searches and tags return no results.

The same principle could be used to generate 403s upon failed login attempts; just create a `403.html` template and modify the content accordingly.

I tried searching the code and found no references that makes use of the `404.html` template

**Comment by virtualtam** [comment]
Hi @k0nsl ,

The 404 template was introduced by #430 / #444, it is rendered in the following situations:
- link not found
- tag not found
- day not found (Daily digest page)

> This could and probably should be used for when searches and tags return no results.

A 404 should only be returned/displayed/rendered when the user/client attempts to access a resource that does not exist.

The situation of a user running a search query that returns no result -either because there are no entries corresponding to the aforementioned query, or said user does not have access to some (private) results- is a nominal case, and will not lead to returning a 404 error page.

Now regarding the addition of a 403 template:
- this would be more suitable for the REST API that is currently being worked on (specs) at https://github.com/shaarli/api-documentation
- we could add a customized login error page to the main UI, but this will have to wait for the template re-design, see #266

**Comment by ArthurHoaro** [comment]
404 is only rendered when a small hash isn't found, despite propositions in #430. Maybe, it can be re-discussed. 

About the login, displaying an error page is not ergonomic. When you mistype your password, you expect to be able to retype it again in the same page (using blank keycaps, you learn that the hard way).

**Comment by nodiscc** [comment]
a 404 page on `day not found` (Daily page) make sense (though the only way to access a non-existing day, is to try to access a manually entered URL - only existing days are linked from the calendar)

For the `tag not found` situation (http://shaarlidemo.tuxfamily.org/Shaarli/?searchtags=doesnotexist) I think the current behavior is fine - Blank list, `Nothing found` message, and it allows you to try another search directly.
