### ISSUE TITLE
Syntax error in Dockerfile production stable and weird behaviour when downloading the stable archive form Github

### ISSUE THREAD

**Issue by krypty** [shaarli/Shaarli#648]
Hello and thanks for supporting Shaarli,

I have the following error when I try to build the stable Dockerfile version of Shaarli.
I think this is caused because of a missing backslash in this Dockerfile.

**Steps to reproduce**
1. git clone https://github.com/shaarli/Shaarli.git
2. cd Shaarli/docker/production/stable
3. docker build -t krypty/shaarli .

Then this error appears :

```
Step 10 : RUN curl -L https://github.com/shaarli/Shaarli/archive/stable.tar.gz | tar xzf -     && mv Shaarli-stable shaarli
 ---> Running in 45b4b401f5bb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    146      0 --:--:-- --:--:-- --:--:--   146
100  606k  100  606k    0     0   264k      0  0:00:02  0:00:02 --:--:-- 1273k
 ---> 3b3b53bb2fc4
Removing intermediate container 45b4b401f5bb
Step 11 : &&
Unknown instruction: &&
```

**Solution**
I have made a pull request to fix this issue.

But it seems that there is an other problem. At the line 26, the Dockerfile runs composer but says that there is no composer.json file. After I curl manually the repository, I was surprised to not find this file too ! So I went to the Shaarli's Github repo and download manually the content of the branch stable using the big green button "Clone or Download" and select the zip archive. After unzipping it, there is still no composer.json file (and many others...).
I don't know if it is a github bug or if this is expected. 

Thank you ;-)

PS : Why there is a stable branch ? The tags on the stable branch are not stable enough ?

**Comment by virtualtam** [comment]
Thanks, PR merged!

> At the line 26, the Dockerfile runs composer but says that there is no composer.json file

You have to checkout the `stable` branch before building a `stable` image, as the `Dockerfile` provided on `master` anticipates changes that have not been released yet, e.g. Composer usage and PHP-cURL features.

The Docker Hub hook builds `stable` images from the `stable` branch.

Regarding the absence of `composer.json` from GH archives: this file was ignored by the `.gitattributes` as Composer was only used to resolve PHPUnit test dependencies, this has been fixed in https://github.com/shaarli/Shaarli/commit/b039a061ebc55f2b62ec3fbead3e4a34666a0aaa

> PS : Why there is a stable branch ? The tags on the stable branch are not stable enough ?

Tagged (released) versions correspond to our milestones, but may contain major/minor bugs and regressions, or provide rough egdes when updating.

The `stable` branch points to the latest Shaarli version that has been released and is known to be stable, i.e. well tested with no sensible regression/bug. This allows Git users to checkout Shaarli on the `stable` branch, while being confident that `git pull` won't wreak havoc on their installation ;-)

**Comment by krypty** [comment]
OK thanks for the explanation. Indeed, it works well if I checkout to the stable branch before.

1. git clone https://github.com/shaarli/Shaarli.git
2. cd Shaarli
3. git checkout stable
4. cd docker/production/stable
5. docker build -t krypty/shaarli .

For me it is all good. Feel free to close this issue if it is no longer useful.

**Comment by virtualtam** [comment]
You're welcome ;-)
