### ISSUE TITLE
PHP7 and the Debian package

### ISSUE THREAD

**Issue by e2jk** [shaarli/Shaarli#650]
Debian is transitioning to PHP7.
The [following bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821656) was opened against the (not updated in along time) `shaarli` Debian package.

Apparently Shaarli is part of the Freedombox, which would like to keep using the package.

I do not have time anymore to spend on either Shaarli (as mentioned a year or so ago) and Debian. Is anyone interested in taking over the packaging, and perform the transition to PHP 7 (and obviously package a much more recent version of Shaarli for Debian)?
I will ask the question to the other co-maintainer of the package (Georges Khaznadar) if he is still active, otherwise we will let Shaarli drop off Debian (and all derivatives such as Ubuntu)

**Comment by nodiscc** [comment]
Hi @e2jk I created https://github.com/shaarli/shaarli-pkg-debian in case someone wants to work on it. I will have a look.

I couldn't import it as a branch here, since it does not share any commits with this repo.

(not interested in becoming a package maintainer since I use ansible/git to manage shaarli) Ping @Freedombox @cat-git @cjbarnes18 @harry-7 @ikmaak @joelvalleroy @jvalleroy @matujo @mikini @nikhilrayaprolu @SunilMohanAdapa

**Comment by virtualtam** [comment]
Hi!

I've raised https://github.com/shaarli/Shaarli/pull/664 to add a well-formatted CHANGELOG to Shaarli; it follows the format proposed at http://keepachangelog.com/en/0.3.0/ and holds the whole history of the Shaarli project (legacy/pre-GitHub releases and community fork releases).

Let me know if it can be of use for inclusion in the Debian package, I'll be happy to work on a parser in case some formatting/curating is needed ;-)

**Comment by nodiscc** [comment]
As of https://github.com/shaarli/shaarli-pkg-debian/commit/eea01ef28607f48ece55c919a08efaa0d8b8c816 this bug has been fixed. In the same time, the `shaarli` package was removed from the Debian package archive.
