### ISSUE TITLE
Descriptions with "<" break site (Markdown plugin)

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#688]
Using release v0.8.0 with Markdown plugin like on http://shaarlidemo.tuxfamily.org/Shaarli :
It seems there are various issues: `<foo>` becomes `<foo>` hence any valid tag is interpreted verbatim on the site. That might just as well be a critical security issue!? _Update:_ At least `<script` is not affected.
`&lt;` is saved as `<`, hence it is not possible to safely enter `<`.
Current workarounds: Disable Markdown plugin, or do not allow public editing, or for private sites, use the `.nomarkdown` tag if descriptions break.

**Comment by xrat** [comment]
Re workaround `.nomarkdown`: This breaks RSS, see #689

**Comment by ArthurHoaro** [comment]
I understand that this behaviour is not really intuitive, however, it's not a bug, it's a feature!

Markdown is supposed to support HTML, for example:

    > <strong>strong</strong><strike>strike</strike>

> <strong>strong</strong><strike>strike</strike>

Github, for instance, seems to use a whitelist of HTML tags available. Shaarli's MD plugin only uses a black list of tags (`script`, `iframe`, etc.) and will otherwise render any HTML tag. If you need to display HTML/XML tags, you can either use the `nomarkdown` as you said, or display it as code: `<inline>` or

    <block>

**Comment by xrat** [comment]
OK, thanks for checking and the explanations. However, I wish there was a warning for sites that upgrade from pre 0.8 to 0.8 with Markdown plugin. When the plugin renders old descriptions/notes including "<" sites are very likely to break in unpleasant ways.

**Comment by ArthurHoaro** [comment]
I suppose I could add it to the plugin's README and/or its description in the admin page.

**Comment by xrat** [comment]
Maybe https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration is more likely to be checked by those who upgrade?

**Comment by ArthurHoaro** [comment]
@xrat the markdown plugin is disabled by default, so it's not really related to the upgrade.

**Comment by xrat** [comment]
@ArthurHoaro You are right. So it's not an issue, especially with all the other changes you made. Thanks a lot!
