### ISSUE TITLE
pagecache empty and not used

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#715]
My `pagecache` directory is empty and is not filled.

I had this problem before on a different host w/ Shaarli 0.8.0 on PHP 5.4 and figured it might be a problem with that particular setup. However, this now affects Shaarli 0.8.1 on PHP 5.6 on a host where it previously worked just fine.

Also, I have no idea how to debug this. The directory exists, it is writable by the user that PHP runs as (PHP-FPM), it is world-readable, no errors in Apache error.log.

**Comment by ArthurHoaro** [comment]
Did you try to access your RSS feed before checking the directory?

**Comment by xrat** [comment]
Nope, I thought it was for HTML too!?

Anyway, I checked the directory, and indeed found 1 file, a cache of the RSS2 feed. Accessing both feeds did not create further files. I then added a new bookmark entry and access the 2 feeds. The entry showed up but `pagecache` was empty afterwards!?

**Comment by ArthurHoaro** [comment]
Yes, Shaarli's different cache mechanisms are a bit confusing. Also, I think we could rearrange the directories tree.

Templates cache is stored in `tmp/` by default. Thumbnails cache is in `cache/`. `pagecache/` is used for "manual" cache in Shaarli's code, mostly (only?) RSS/ATOM feeds.

For `pagecache`, the first time a visitor will access a feed, it'll create a cache file. Then, next visitors will be served this cache file. Until you change anything (like adding a link), which will invalidates all existing cache files.
Note that cache files aren't created as logged in, because it includes private links.

**Comment by xrat** [comment]
OK, that explains it all. Of course, I was logged in when I loaded the feeds. My `pagecache` is filled when the feeds are publicly accessed.
Thank you very much!
