### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by nicolasdanelon** [shaarli/Shaarli#89]
What if we add a changelog file like [this one](https://github.com/GNOME/geary/blob/master/debian/changelog) here in the repo?

And a new link in the footer with the subversion date or number like this:

[Shaarli 0.0.41 beta](http://sebsauvage.net/wiki/doku.php?id=php:shaarli) - The personal, minimalist, super-fast, no-database delicious clone. By [sebsauvage.net](http://sebsauvage.net/). Theme by [idleman.fr](http://blog.idleman.fr/). 
[Comminuty](https://github.com/shaarli/Shaarli/wiki/history) [version 0.1.6](https://github.com/shaarli/Shaarli/blob/master/changelog)

And maybe we can create a history page in the wiki to tell to the people [why this fork](https://github.com/sebsauvage/Shaarli/issues/191#issuecomment-68188141) :)

**Comment by nodiscc** [comment]
The next footer should be:

[https://github.com/shaarli/Shaarli](Shaarli) -- The personal, minimalist, super-fast, no-database delicious clone. By [sebsauvage](http://sebsauvage.net/) and [contributors](https://github.com/shaarli/Shaarli/blob/master/COPYING).

(We should not display the version number to visitors, bur rather only display it in `?do=tools`.)

Yes we should definitely add a word about "why this fork" in https://github.com/shaarli/Shaarli#about

**Comment by nicolasdanelon** [comment]
what do you think @nodiscc ?

**Comment by nodiscc** [comment]
I think it's a bug and should be fixed before releasing 0.9beta

**Comment by nicolasdanelon** [comment]
@nodiscc I got a problem with this... If a ''cracker'' see my shaarli and he know that we got the code here in GitHub he can get the version of shaarli accesing the URL http://host.com/shaarli_version.txt
**we need to add a .htaccess file to restrict this access!**

**Comment by nicolasdanelon** [comment]
cat .htaccess 
RewriteEngine on                                                            
RewriteRule \.txt$ - [R=404]

**Comment by e2jk** [comment]
@nicolasdanelon I do agree that we shouldn't disclose the version ID (as explained by @nodiscc in his the second post here), but I'm somewhat confused by your message indicating you have a problem with this, since in the very first post you even suggesting putting the "subversion date or number" in the footer ;)

Anyway, this is somewhat similar to https://github.com/sebsauvage/Shaarli/issues/214 and https://github.com/sebsauvage/Shaarli/issues/214 although it doesn't involve the version number in the HTML, but rather that there is a file at a fixed location that contains the Shaarli version. I have opened a new issue #122 to track that separately.

**Comment by nicolasdanelon** [comment]
In the beginning I want to show the community version in the footer BUT now I see the power of that... And I don't "want" that feature any more.  Because of that I think that we need to add a htaccess file with that restriction. @e2jk @nodiscc :)

**Comment by nodiscc** [comment]
@nicolasdanelon htaccess is apache specific. See Pull request https://github.com/shaarli/Shaarli/pull/123

**Comment by dper** [comment]
Security through obscurity is not a great strategy.  Hiding the version number won't stop attackers.

**Comment by nicolasdanelon** [comment]
@nodiscc I like the pull #123 but the current version is using .htaccess in cache, data, pagecache, tmp....  So.... ? index.php should deliver everything like in Laravel or WordPress does?
someone wants to add symfony components to Shaarli.. Maybe for a refactor is finally the time :P

**Comment by nodiscc** [comment]
files in `data/` and `pagecache/` are obfuscated in the same way I did in #123 (.php file extension, datastore contents are commented out). `cache/` doesn't leak information unless you are able to enumerate the files in it. `.htaccess` files are just a convenience. Version disclosures are non-issues as said above. Feel free to rewrite Shaarli if you have some time.

**Comment by nicolasdanelon** [comment]
@nodiscc @e2jk this is the last comment here. I promise. if we *obscure* the version N° in the footer what about this?

![screenshot from 2015-03-03 18 01 54](https://cloud.githubusercontent.com/assets/2846046/6472217/8e7f5fa2-c1cf-11e4-8bc7-b75e627d70bd.png)

thanks! :) good work, I will use community version in my server since tomorrow

**Comment by nodiscc** [comment]
@nicolasdanelon Well spotted! I'll remove that, not because it discloses the current version, but because it has no purpose. It's there to prevent browser from using old, cached stylesheets, but anyway we use the `no-cache` header that prevents caching (even if this is bad for performance, we re-download the CSS on every page request).

**Comment by nicolasdanelon** [comment]
@nodiscc  what about put date("YM") so we can have a decent cache time ?

**Comment by e2jk** [comment]
Let's discuss this specific issue further in #134.
