### ISSUE TITLE
0.9.0 is a lot slower than older version 0.6.x

### ISSUE THREAD

**Issue by mum1989** [shaarli/Shaarli#891]
0.9.0 is laggy for me

(Debian Jessie 
Atom J1900
4go ram
500Go HDD

slow to publish, slow to edit, even next to my srv (same network)
 autocompletion is very slow too

**Comment by ArthurHoaro** [comment]
Hi. TBH, it'll be difficult to debug, and it's working pretty fine everywhere (e.g. on the demo).

How many links do you have? Which PHP version are you using? Does it happen with both themes? Which webserver are you using? How is your server load?

**Comment by mum1989** [comment]
16145 shaares
using stock/defaut  theme

Debian GNU/Linux 8.8 (jessie)

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
apache2

my server load is (very) low
(for an example on same srv, i have FreshRSS it's works fine , no slow down

thanks

**Comment by ArthurHoaro** [comment]
Thanks. I'm currently generating a large datastore to make further tests. However,

> autocompletion is very slow too

Autocompletion is client side only and didn't really change since the v0.6.0.

**Comment by mum1989** [comment]
ok Thanks

**Comment by ArthurHoaro** [comment]
I've monitored execution times in `v0.9.0` with a 50MB database (around 10k links with roughly 50kB by link). It is pretty slow. ≃1.2 seconds for `LinkDB ` to load with a 4 years old i5 and PHP built-in server.

I didn't bother to compare with `v0.6.x` but I'm pretty sure that the difference you feel comes from the new ID system, due to: 

  * the function `LinkDB::reorder()` called every time (2 links iterations) - easy to fix, it should only be called when we save the links.
  * the ArrayAccess has another layer to map the real IDs - impossible to fix, but it might be negligeable.

I see two ways of improvements aside from `reorder` calls:

   * use a cache system
   * with LinkDB refactoring (#445), let users choose between either a flat file datastore, or a proper RDBMS.

**Comment by mum1989** [comment]
ok thanks  a lot.
I thinks the same about RDBMS, it's probably necessary .

**Comment by mum1989** [comment]
shaarli is faster on Opera (Chrome engine)

**Comment by nodiscc** [comment]
@mum1989 Since you can't reproduce this bug on another browser, and your server load is very low, I assume it was a browser-related problem? What was the browser where the problem used to appear (Firefox?) ? If Firefox, can you  reproduce it with a [fresh Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), without addons/etc?

I am curious because I didn't notice any performance degradation - my Shaarli serves ~6000 shaares on a single-CPU-core VM with 1024MB RAM, running on a Debian 9 laptop, which also runs my browser (Firefox ESR 52).

Please try to reproduce with a fresh browser profile.

**Comment by virtualtam** [comment]
Closing due to lack of feedback.
