### ISSUE TITLE
Tools - Import links - Shaarli should filtered out meta characters

### ISSUE THREAD

**Issue by Esak8** [shaarli/Shaarli#892]
Hi,

While importing bookmarks, Shaarli shouldn't create tags that start with meta characters.

For instance, I have the followings bookmarks on Safari :  

![safari_bookmarks](https://cloud.githubusercontent.com/assets/28948020/26760044/459c3c6e-490f-11e7-9693-267677c40ccc.png)

For the folder **Github - Shaarli**, Shaarli creates 3 tags :  
- `github`
- `-`
- `shaarli`

![tags_shaarli](https://cloud.githubusercontent.com/assets/28948020/26760054/7f3ffad2-490f-11e7-9e06-48733228eb0e.PNG)

The behavior seems to be the same regardless of the web browser used.

Here is the file used for the test (minus the `.txt`) [safari.html.txt](https://github.com/shaarli/Shaarli/files/1050196/safari.html.txt)

**Comment by virtualtam** [comment]
Hi @Esak8 !

This behaviour is due to how bookmarks are parsed, stored internally and displayed:
1. [netscape-bookmark-parser](https://github.com/shaarli/netscape-bookmark-parser)
    - reads the headers correctly: `Github - Shaarli`
    - converts the string to lowercase: `github - shaarli`
2. Shaarli
    - uses this value as-is when importing bookmarks
    - considers there are 3 space-separated tags: `github`, `-`, `shaarli`

We could add an option to the parser to allow either:
- stripping spaces from folder names: `github-shaarli`
- stripping punctuation from tag names: `github`, `shaarli`
