### ISSUE TITLE
New plugin : @notify

### ISSUE THREAD

**Issue by Lucas-C** [shaarli/Shaarli#907]
Hi,

I'm opening this to discuss a new plugin I want to create.

In short, the idea is the following:
1- A shaarli instance owner can configure a list of "contacts" (cf. below)
2- When he adds a new link, he can includes an "@FriendName" mention in the link description
3- This contact will be sent a notification note with a permalink

**ConfigManager:**
Each contact is associated with exactly one notification system: email, facebook or shaarli
Example entries:
```
- name: @Matt
  email: ...
- name: @Sarah
  facebook: ...
- name: @ArthurHoaro
  shaarli: ...
```

**Technical details:**
- Shaarli hook used: `save_link`
- for emails, I guess the standard PHP function would be enough, as long as the user server has SMTP configured
- for Facebook contacts, a single API token would be required, and I think this could be used: https://developers.facebook.com/docs/php/howto/example_post_links
- for Shaarli contacts, they would have to share their API token with the user so that the plugin could post a notification link on their instance.
I don't really like this idea, but I don't have a better one so far.
Maybe shaarli contacts aren't a good idea, what do you think ?

**My questions:**
- what do you think of this plugin idea ?
- I guess the user configuration should be stored in the ConfigManager like [this](https://github.com/ArthurHoaro/shaarli2twitter/blob/master/shaarli2twitter/shaarli2twitter.php#L283).
Can it support a list ?
- how to ensure notifications are not re-sent on link edition ?
I don't want to add an extra datastore for this, so I thought about editing the link in the database to reflect that users were already notified.
E.g. the user syntax would be to add a double-@ prefix in front of contact names, but the plugin would transform `@@ContactName` into `@ContactName` to ensure it does not apply a 2nd time.
- how to give feedback to the user that contact notifications were successfully sent ?

**Comment by virtualtam** [comment]
Hi @Lucas-C !

That's a tough one to answer, sorry in advance if things get messy 🎢 

> what do you think of this plugin idea ?

This actually looks like an idea for several plugins/services/features:
- email notification (see [PHPMailer](https://github.com/PHPMailer/PHPMailer))
- 3rd-party API clients (see [Guzzle](http://docs.guzzlephp.org/en/stable/) & Shaarli HTTP utilities)
- inter-Shaarli communication / syndication

> for Shaarli contacts, they would have to share their API token with the user so that the plugin could post a notification link on their instance.
> I don't really like this idea, but I don't have a better one so far.

There are several limitations due to Shaarli's design and technical choices that were/are made:
- single-user
- no underlying relational database management system

The following are needed to provide this feature in a safe fashion:
- handle several API tokens
- handle token <-> permissions to grant external users with limited privileges
- handle token revocation

Then additional processing might be required/desired:
- special processing for links coming from ~~outer space~~ external users, e.g. additional tags, edited title, etc.
- link filters to easily find content added from external sources

> I guess the user configuration should be stored in the ConfigManager like this.
Can it support a list ?

This indeed requires some kind of user and permission management, which is currently absent from Shaarli because of its _personal usage_ nature, and goes beyond the scope of a mere plugin, as it implies changing how content is stored and accessed.

> how to ensure notifications are not re-sent on link edition ?

Link creation and last edition (if different) dates are stored, so you can emit a notification after creation only

> Maybe shaarli contacts aren't a good idea, what do you think ?

I think there's a broader question here, that is whether Shaarli can be used as a social network component :)

IMHO Shaarli should be kept as simple as possible, and stay focused on managing a single user's links efficiently. Managing multiple users and permissions would require a complete redesign of the application's internals.

This means that any interaction with other environments should be handled by separate, dedicated tools such as webservices and middleware.

To this effect, existing core features can be leveraged and extended:
- Atom/RSS feeds to notify subscribers of new content
- REST API to manage content

Considering the initial scenario:

> 1- A shaarli instance owner can configure a list of "contacts" (cf. below)
> 2- When he adds a new link, he can includes an "@friendname" mention in the link description
> 3- This contact will be sent a notification note with a permalink

You could easily write a middleware that:
- subscribes to friends' Shaarli Atom feeds
- periodically aggregates new content
- if a new item contains specific information (e.g. `@someone` mention), then perform certain tasks, such as:
    - adding new entries to your Shaarli instance using the API
    - sending mail/3rd-party notifications
    - ...

**Comment by Lucas-C** [comment]
Thanks a lot for your answer !
You addressed all my interrogations in details :+1: 

I totally agree that Shaarli should stay simple, and focus on doing one thing well.

I really like your idea of using RSS here.
Maybe there is another interesting use case for it, that needs absolutely zero work:
because Shaarli already provides an RSS stream filterable by tags, I can simply add a @user tag and bingo, I have a per-contact dedicated RSS stream ! https://chezsoi.org/shaarli/?do=atom&searchtags=%40Matt

I think I'm going to try to convince friends to adhere to this system :)

If you think this is an interesting solution, maybe Shaarli could simply suggest this mechanic through a well placed help text.

**Comment by Lucas-C** [comment]
Just FYI, I found to free solutions to convert RSS to emails:
- https://ifttt.com/applets/147561p-rss-feed-to-email
- https://mailchimp.com/features/rss-to-email/

**Comment by nodiscc** [comment]
I have found other self-hosted/Free Software solutions that can forward RSS feeds as email:

 * https://github.com/wking/rss2email `Python `
 * https://github.com/foxmask/django-th `Python`
 * https://kibitzr.github.io/ `Python`
 * https://github.com/huginn/huginn `Ruby`
 * https://github.com/muesli/beehive `Go`

Another way to achieve this would be to extend https://github.com/shaarli/python-shaarli-client to periodically check your Shaarli, and forward the RSS feed as email to your chosen recipients, based on rules (tags? post content? etc).

@Lucas-C did you find a reliable way to make this work?

**Comment by Lucas-C** [comment]
Thanks for sharing your findings !

As I explained above, I opted for the solution to add @userName tags on links I want to share with friends, and gave them the URL RSS feed with this tag filter set.

I'm closing this, as this solution fits my need.

If anyone wants to give a go at some of the ideas described here, feel free to reopen this issue.
