### ISSUE TITLE
Change tag suggestions behavior?

### ISSUE THREAD

**Issue by s1dh** [shaarli/Shaarli#92]
In my workflow I open a new browser window per subject of interest and I open as many tabs as needed during my searching session. The result is I often end this search session with dozen of interesting links I would like to bookmark . As all links could be tagged with almost the same 'keywords' , it would be great to press e.g. the down arrow in the tags field and have a scroll down list of the X last tag sequences chosen (X could be set as a parameter) and select the convenient tag sequence for all the links of the same window I want to bookmark. Of course I could add /remove one tag of the sequence If needed.

This way it would be quicker to save a bunch of links that deal with the same subject (keywords).

**Comment by nodiscc** [comment]
Down arrow does nothing currently, yes it could suggest most recent tags (store them in a cookie? ... ?)

As a workaround, when bookmarking a batch of pages, you can CTRL+C your first tags, and paste them in the next link tags. Is this solution ok for now?

**Comment by nodiscc** [comment]
Related https://github.com/shaarli/Shaarli/issues/49

**Comment by pikzen** [comment]
Generating a list of suggestions would be as easy as outputting a javascript object and using it to suggest data. That requires changing how the <input>s currently in use work.

**Comment by nodiscc** [comment]
I think adding this is a very small improvement/hack over the previous code.

If we're going to change how suggestions work, i would suggest basing them on [frecency](https://en.wikipedia.org/wiki/Frecency) instead - as I said CTRL+C/CTRL+V works in @s1dh case.

The suggestions should take into account:
 * what is currently being typed in the field
 * most used tags
 * most recent tags
 * (optional) the page's contents (meta tags, body?)

Only adding this down-arrow trick is a very partial solution. It's a good idea anyway.
Comments on how you would like suggestions to behave are welcome.

**Comment by s1dh** [comment]
Frequency would not reflect a sequence if I understand correctly what you mean. It would just create an artificial (out of context) sequence of tag based on most popular tags.
 
Of course ctrl+c/v works but it's not handy, cycling through the X last tag sequence with (e.g.) down arrow key would be simpler imo ! 

why not let the user choose with  a history/frequency/other mode configuration parameter.

**Comment by s1dh** [comment]
@nodiscc for testing @ArthurHoaro's file, I did git clone https://github.com/ArthurHoaro/Shaarli.git from my development web server and gave it a try ... Is this wrong ?

**Comment by nodiscc** [comment]
> cycling through the X last tag sequence with (e.g.) down arrow key

This is also artificial and out of context most of the time.

**Comment by s1dh** [comment]
It depends of your workflow. Suppose each time you have to search on a specific topic you open a new window in your browser (one window per specific topic) this window will contain all the tabs with relevant results of your searchs. So in one window, all tabs more or less refer to the same "tags sequence" . 

So, for each tab you want to keep in shaarli in this context, displaying the (X) last tag sequence could fill 90% of your tag field by the time of pressing the DOWN arrow key, and from then, you could only complete (add/delete some tag) your tag sequence very quickly, if needed.

**Comment by nodiscc** [comment]
I'll close this for now; it was decided in https://github.com/shaarli/Shaarli/issues/49 that the best course of action is switching to [awesomplete](https://github.com/LeaVerou/awesomplete) for autocompletion in the first time, and remove jQuery. @s1dh's workflow is valid, but really an edge case (see comments in the other issue). Once awesomplete support is in, we can discuss this again.

There was discussion about batch-adding links (which is what @s1dh wants to improve) in https://github.com/shaarli/Shaarli/issues/115. I think a batch "add multiple links" feature is what's needed here, not hacking the autocompletion behavior. Please open a separate issue for it if needed.

For all UI-related matters, please try to attach screenshots/mockups of expected behavior, even if it's a dirty mspaint draft. Helps keeping things clear. For now you can use CTRL+C/CTRL+V. Eg your suggestion, if I understood it well (draft with [xournal](https://packages.debian.org/jessie/xournal))

![unfold](https://cloud.githubusercontent.com/assets/3950390/6480568/5fbd39e2-c255-11e4-87d3-12fe30f09336.png)
