### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#930]
### Issue
In the Plugin Configuration Page, the "More plugins available in the documentation." link points to the former local documentation location, and should now point to either:
- the local documentation (if present / generated by the user)
- the online documentation on RTFD

### Suggestions
Maybe we can provide a setting so users can choose which version of the docs is referenced?

Also, there should be a robots.txt under `doc/html` to prevent bots from indexing users's docs: [Google search on "shaarli server requirements"](https://encrypted.google.com/search?hl=en&q=server+requirements+shaarli&oq=server+requirements+shaarli&gs_l=psy-ab.3...25733.28299.0.28711.20.12.0.0.0.0.377.1808.0j1j5j1.7.0....0...1.1.64.psy-ab..18.0.0.BBvN2PvSA-w)

**Comment by nodiscc** [comment]
I have started looking into it. There are 3 broken llinks as far as I know:

```bash
$ cd tpl/; git grep "doc/"
default/page.footer.html:    <a href="doc/html/index.html" rel="nofollow">Documentation</a>
default/pluginsadmin.html:        <a href="doc/Community-&-Related-software.html#third-party-plugins">in the documentation</a>.
vintage/page.footer.html:  - <a href="doc/Home.html" rel="nofollow">Help/documentation</a>
```

> Maybe we can provide a setting so users can choose which version of the docs is referenced?

Would it be OK to simply hardcode it to point to the local documentation? Since the HTML doc is part of the release archives? -> https://github.com/shaarli/Shaarli/blob/master/Makefile#L162. There is a link to https://github.com/shaarli/Shaarli in the footer anyway. Then add manual documentation build steps to https://github.com/shaarli/Shaarli/blob/master/doc/md/Download-and-Installation.md#using-git ?

> there should be a robots.txt under doc/html
> Google search on "shaarli server requirements"

Yes there probably should :)

**Comment by virtualtam** [comment]
> Would it be OK to simply hardcode it to point to the local documentation?

I guess so :)

> robots.txt

On second thoughts, I'm not sure how it would behave when running Shaarli behind one or more reverse proxies?

Maybe it should be handled through the HTTP server / proxy configuration as shown in https://stackoverflow.com/questions/1090823/how-do-i-configure-nginx-to-redirect-to-a-url-for-robots-txt-sitemap-xml

**Comment by nodiscc** [comment]
See https://stackoverflow.com/questions/38305272/robots-txt-for-application#38305597

Since we cannot know the desired robots.txt configuration for every instance (administrator may want to set custom robots rules, shaarli may be installed alongside other applications, etc), I think it is best not touch the server's configuration regarding this file. What we could do is:

 - Document robots.txt usage on the Server Configuration page in the docs
 - Disallow indexing of doc pages via `<meta>`-tags as suggested in the SO answer above
