### ISSUE TITLE
Display the page name in the HTML page title

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#955]
Relates to #954

**Comment by smth** [comment]
Is this in relation to the main/landing page putting the title of the first link in the `title` tag? I would expect it show the title ("Shaarli title") as configured under "Tools", which is what already happens on every other page (the other pages should probably have more nuanced titles).

**Comment by nodiscc** [comment]
@smth I believe this relates to

 * https://github.com/shaarli/Shaarli/issues/954 (Display the search terms in the HTML page title) - anytime there is some filtering applied (plain text or tags)
 * Pages like the tag cloud currently only display the "Shaarli title". It would be nice to have `Tag cloud - Shaarli title` (same thing for picwall, tools pages...)

Already fixed:

 * The main/landing page only puts the first link title in the HTML page title when there is ONLY one link displayed, with the "Shaarli title" appended to it. eg. the title for https://demo.shaarli.org/?searchterm=shaarli&searchtags= is `The personal, minimalist, super-fast, database free, bookmarking service - Shaarli demo (master)` <- is that correct?

**Comment by smth** [comment]
That last issue is the one I wanted to raise, wasn't sure if it was captured anywhere. So it's fixed, but not in current release?

**Comment by nodiscc** [comment]
> So it's fixed, but not in current release?

Uh, it has worked this for longer than I can remember, see https://github.com/shaarli/Shaarli/issues/399 from 2015, the page title was already `<title of the link> - <Shaarli title>`. Or does this not work for you?

**Comment by smth** [comment]
It doesn't work as I'd expected, when there is only one link displayed. But it sounds like this is intentional.

**Comment by virtualtam** [comment]
Hi!

This issue is deliberately open for discussion to settle upon a behaviour that makes the most sense for users.

Suggestion:

- `Bookmarks | Main title title` for the main page, with no search criterion
- `<search criteria> - <page name> | Main title` for pages providing a search module (link list, tag list, feeds, etc.)
- `<link title> | Main title` when selecting a given link (#399)
- `<page name> | Main title` for other pages as mentioned by @nodiscc in https://github.com/shaarli/Shaarli/issues/955#issuecomment-346310266

By reading the comments here, it appears that the search case has some subtleties to it (single result, no result), so feel free to post suggestions to #954 :)

**Comment by smth** [comment]
It was the main page that was troubling me, but to be fair I hadn't realised that the behaviour of using a link title as the page title was restricted to scenarios where there is only one link. While it still doesn't feel quite right to me, I think this is an exceptional case, and one that I have less strong feelings about (than if it was always the case).

Your suggestions look reasonable to me. Though perhaps prepending "Bookmarks" in the main page title is unnecessary and potentially problematic. Unnecessary because the main title will likely be describing this overarching function, i.e you might end up with `Bookmarks | My Bookmarks`. Problematic because the use case might not be strictly bookmarks, or that might not be the desired terminology (someone might want to use "directory", or "reading list" for example). Seems to me that having that term hard-coded will cause more problems than it solves.

**Comment by ArthurHoaro** [comment]
I agree with your suggestions 👍 

As for including the link title if there is only one link, a more logical solution would be to only include it if we're on a permalink.

**Comment by nodiscc** [comment]
> As for including the link title if there is only one link, a more logical solution would be to only include it if we're on a permalink.

Yes :+1: and :+1: also for @virtualtam's suggestions

**Comment by virtualtam** [comment]
[Everyone gets a 👍!](http://s2.quickmeme.com/img/d7/d71c48482758e1f805c284306467017d271cce6f2d076e77680dcaf6b0cb8f8f.jpg) ;-)

**Comment by ArthurHoaro** [comment]
Fixed by 980efd6
