### ISSUE TITLE
Add the version to the CSS file to prevent cache issues

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#965]
Currently, Shaarli's CSS is cached by the browser and may not update even if it changed depending on the web server configuration.

An easy trick around that is to use `file.css?<version>` instead of just `file.css`, which makes the CSS URL change when Shaarli is updated.

Might also apply to external JS.

**Comment by kalvn** [comment]
Good idea. 

A common practice is also to calculate a short unique hash (8 chars for example) at each release and to use it instead of the version. It would prevent leaking the version number which is supposed to stay hidden for security reasons (although I suppose using the hash to find the version would be quite easy to do, except if each instance has its own "salt" to create the hash).

**Comment by ArthurHoaro** [comment]
Good idea. Each instance already has a hash used for credentials.
