### ISSUE TITLE
"File bookmarks_all_xxx.html has an unknown file format. Nothing was imported"

### ISSUE THREAD

**Issue by TheNomad11** [shaarli/Shaarli#969]
I exported my bookmarks from shaarli (newest version) and tried to import it in another shaarli instance. Then I got this error message

"File bookmarks_all_20170917_231302.html (1139620 bytes) has an unknown file format. Nothing was imported".

The file is 1,1 MB big.

I then made the file smaller, including only one entry. Then the import worked fine. 

Are there issues with larger files? Why do I get an error message about the file format being invalid?

**Comment by virtualtam** [comment]
Hi @TheNomad11 !

What are the respective Shaarli versions and HTTP server configurations?

Also, are the HTTP server and PHP properly configured to allow uploading files >= 1 MiB?

**Comment by izumitelj** [comment]
Hi @virtualtam I think I have the same problem. 

My original file is 1072 KB, exported from Diigo. When importing I got the same message `File xyz.html (1097148 bytes) has an unknown file format. Nothing was imported`

After trimming the file (while trying to figure if this is the problem with syntax or specific characters) I've found that the problem is really in file size. File trimmed to `100221` bytes imports OK while file with
`100222` bytes throws the error.

My server configuration:
```
Apache Version  2.4.25
PHP Version     5.6.30
Architecture    x86_64
Operating System    linux
```
Some of my PHP settings:
```
max_execution_time   90 
max_input_time   60 
memory_limit   128M 
upload_max_filesize   2M
```
I'm not administrator of this server but I can ask for changes if that is the problem.

**Comment by virtualtam** [comment]
Hi @izumitelj !

What is the value for the PHP  `post_max_size` setting?

**Comment by izumitelj** [comment]
@virtualtam here it is:
```
post_max_size  64M
upload_max_filesize  32M
```

**Comment by izumitelj** [comment]
@virtualtam It seems like this has to do with PHP version. The issue is present with PHP 5.6, while with PHP 7 it works as expected without errors. 

Unfortunately I can't switch to PHP 7 yet :(. 

Can someone look into this issue, probably ``NetscapeBookmarkUtils.php``, or at least revisit the  [documentation.](https://shaarli.readthedocs.io/en/master/Server-requirements/)

Thanks

**Comment by virtualtam** [comment]
OK, just to sum things up, could you provide us with the following information so we can try to reproduce the issue?

- Server type (dedicated/bare metal, VPS, container appliance...)
- System:
    - Linux distribution and version code/number
    - architecture (x86, x86_64, etc.)
- Apache:
    - version
    - enabled modules
- PHP:
    - version
    - enabled extensions
    - configuration file location
    - values for `post_max_size` and `upload_max_filesize`

---

Note:

PHP provides different configuration files (one per environment: apache2, cli, fpm, etc.), be sure to check values from the one used by the actual HTTP server (Apache2 / Nginx+FPM, etc.)

---

Example on a dedicated server running Debian 8 Jessie, using Apache 2.4 and PHP 5.6:

```bash
$ uname -a
Linux myserver 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie

$ dpkg -l apache2 | grep ^i
ii  apache2        2.4.10-10+deb8u10 amd64        Apache HTTP Server

$ dpkg -l php5 | grep ^i
ii  php5           5.6.30+dfsg-0+deb8u1 all          server-side, HTML-embedded scripting language (metapackage)

$ grep post_max /etc/php5/apache2/php.ini
post_max_size = 501M

$ grep upload_max /etc/php5/apache2/php.ini
upload_max_filesize = 500M
```

---

In the meantime, I'll write a tool to generate dummy bookmark files of configurable size, to run tests against different environments.

**Comment by izumitelj** [comment]
With release ``` 0.9.2``` I've successfully imported my bookmarks (1.098.716 bytes, 4583 links) without need to split the file in half. It took some time to process but worked.
